### ISSUE TITLE
我正在尝试移植xformers到amd显卡

### ISSUE THREAD

**Issue by Boom-Hacker** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#105]
手动编译版xformer0.0.16安装后速度的确快了，但是在最后最终生成时崩溃了:
[Tiled Diffusion] ignore tiling when there's only 1 tile :)
100%|███████████████████████████████████████████| 20/20 [00:54<00:00,  2.72s/it]
Error completing request:30,  2.64s/it]                                         
Arguments: ('task(e835pofx4v70pp3)', '', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, True, 'MultiDiffusion', False, 10, 1, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, True, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, False, True, True, False, 960, 64, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "/home/darksun0031/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/home/darksun0031/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/home/darksun0031/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/home/darksun0031/stable-diffusion-webui/modules/processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "/home/darksun0031/stable-diffusion-webui/modules/processing.py", line 655, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "/home/darksun0031/stable-diffusion-webui/modules/processing.py", line 655, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "/home/darksun0031/stable-diffusion-webui/modules/processing.py", line 440, in decode_first_stage
    x = model.decode_first_stage(x)
  File "/home/darksun0031/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/home/darksun0031/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/home/darksun0031/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/darksun0031/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "/home/darksun0031/stable-diffusion-webui/modules/lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  File "/home/darksun0031/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "/home/darksun0031/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/darksun0031/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/model.py", line 631, in forward
    h = self.mid.attn_1(h)
  File "/home/darksun0031/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/darksun0031/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/model.py", line 258, in forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=self.attention_op)
  File "/home/darksun0031/stable-diffusion-webui/venv/lib/python3.10/site-packages/xformers-0.0.16+6f3c20f.d20230405-py3.10-linux-x86_64.egg/xformers/ops/fmha/__init__.py", line 197, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/home/darksun0031/stable-diffusion-webui/venv/lib/python3.10/site-packages/xformers-0.0.16+6f3c20f.d20230405-py3.10-linux-x86_64.egg/xformers/ops/fmha/__init__.py", line 293, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/home/darksun0031/stable-diffusion-webui/venv/lib/python3.10/site-packages/xformers-0.0.16+6f3c20f.d20230405-py3.10-linux-x86_64.egg/xformers/ops/fmha/__init__.py", line 309, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "/home/darksun0031/stable-diffusion-webui/venv/lib/python3.10/site-packages/xformers-0.0.16+6f3c20f.d20230405-py3.10-linux-x86_64.egg/xformers/ops/fmha/dispatch.py", line 95, in _dispatch_fw
    return _run_priority_list(
  File "/home/darksun0031/stable-diffusion-webui/venv/lib/python3.10/site-packages/xformers-0.0.16+6f3c20f.d20230405-py3.10-linux-x86_64.egg/xformers/ops/fmha/dispatch.py", line 70, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 4096, 1, 512) (torch.float32)
     key         : shape=(1, 4096, 1, 512) (torch.float32)
     value       : shape=(1, 4096, 1, 512) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    max(query.shape[-1] != value.shape[-1]) > 128
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    max(query.shape[-1] != value.shape[-1]) > 128
    requires A100 GPU
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 512

我的显卡型号是5500xt 4g,半数被阉割了，所以请问有没有办法把这个任务丢给cpu,或者如果您有未阉割半数的amd显卡的话可以帮我试一下吗

**Comment by Boom-Hacker** [comment]
git clone https://github.com/facebookresearch/xformers.git
cd xformers
git submodule update --init --recursive
python setup.py build
python setup.py install

**Comment by pkuliyi2015** [comment]
没有时间解决无关问题，还请自行处理
