### ISSUE TITLE
Not compatible with xformers 0.0.18

### ISSUE THREAD

**Issue by LovElizabeth** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#108]
xformers officially upgrade to version 0.0.18. It seems multidiffusion-upscaler not compatible with newly version of xformers . I got this in console:

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\img2img.py", line 172, in img2img
    processed = process_images(p)
  File "D:\stable-diffusion-webui\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "D:\stable-diffusion-webui\modules\processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\stable-diffusion-webui\modules\processing.py", line 1087, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "D:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 331, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "D:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 331, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 553, in sample_dpmpp_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 152, in forward
    devices.test_for_nans(x_out, "unet")
  File "D:\stable-diffusion-webui\modules\devices.py", line 152, in test_for_nans
    raise NansException(message)
modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.

I am using python: 3.10.10  •  torch: 2.0.0+cu118  •  xformers: 0.0.18  •  gradio: 3.23.0 and windows10 as env.

Hope someone could fix this. Thanks!

**Comment by LovElizabeth** [comment]
> Testing it, and it specifically seems to be something in the _img2img_ pipeline; trying it out in text2img gave no problems even with torch 2.0 and xformers 0.0.18.
> 
> It's not actually solved by avoiding the half VAE thing; I never run that. Always full precision VAE here.

yes, it's occurring when I use img2img. The half precision something not helping. Hope it could be fix soon.

**Comment by LieDeath** [comment]
Try the VAE-ft-mse-840000? The VAE which is recommanded by Stablity AI.

**Comment by LovElizabeth** [comment]
> Try the VAE-ft-mse-840000? The VAE which is recommanded by Stablity AI.

sorry but I think it's not VAE got problem, whatever I turn on or turn off VAE or changed the VAE to VAE-ft-mse-840000 or another, It's just not working and console gives similar log as before.

**Comment by RainehDaze** [comment]
> Try the VAE-ft-mse-840000? The VAE which is recommanded by Stablity AI.

I was already using a model-specific VAE that prevents a lot of the black boxes. And disabling half VAE.

It's not a settings thing; it's an incompatibility with newer versions of torch and xformers. No black box problems on the current versions that A1111 uses (1.13 and 0.0.16), but if you try and do any img2img with new versions, you'll get this error. 

(I'm not sure if it's to do with the tiled VAE or multidiffusion specifically, I'd need to check which)

**Comment by LieDeath** [comment]
> > Try the VAE-ft-mse-840000? The VAE which is recommanded by Stablity AI.
> 
> sorry but I think it's not VAE got problem, whatever I turn on or turn off VAE or changed the VAE to VAE-ft-mse-840000 or another, It's just not working and console gives similar log as before.

Well, it sounds annoying, maybe disable the xformers and just enable the Scaled Dot Product cross attention optimization is better.

**Comment by RainehDaze** [comment]
> > > Try the VAE-ft-mse-840000? The VAE which is recommanded by Stablity AI.
> > 
> > 
> > sorry but I think it's not VAE got problem, whatever I turn on or turn off VAE or changed the VAE to VAE-ft-mse-840000 or another, It's just not working and console gives similar log as before.
> 
> Well, it sounds annoying, maybe disable the xformers and just enable the Scaled Dot Product cross attention optimization is better.

Probably worth trying (I'd need to install torch 2.0 again).

I'd guess the things to test are
1. Without xformers
2. Tiled VAE only, no multidiffusion (just use a big image to start with)
3. Multidiffusion, no tiled VAE.

See if that narrows down what's causing the issue

**Comment by LieDeath** [comment]
> > Try the VAE-ft-mse-840000? The VAE which is recommanded by Stablity AI.
> 
> I was already using a model-specific VAE that prevents a lot of the black boxes. And disabling half VAE.
> 
> It's not a settings thing; it's an incompatibility with newer versions of torch and xformers. No black box problems on the current versions that A1111 uses (1.13 and 0.0.16), but if you try and do any img2img with new versions, you'll get this error.
> 
> (I'm not sure if it's to do with the tiled VAE or multidiffusion specifically, I'd need to check which)

How about using the xformers 0.0.17rc482 instead? I test and confirm that this older version is workable.

**Comment by RainehDaze** [comment]
> > > Try the VAE-ft-mse-840000? The VAE which is recommanded by Stablity AI.
> > 
> > 
> > I was already using a model-specific VAE that prevents a lot of the black boxes. And disabling half VAE.
> > It's not a settings thing; it's an incompatibility with newer versions of torch and xformers. No black box problems on the current versions that A1111 uses (1.13 and 0.0.16), but if you try and do any img2img with new versions, you'll get this error.
> > (I'm not sure if it's to do with the tiled VAE or multidiffusion specifically, I'd need to check which)
> 
> How about using the xformers 0.0.17rc482 instead? I test and confirm that this older version is workable.

With Torch 2.0? I can't remember when xformers stopped using 1.13 and started using 2.0; it was some time between the beta versions of 0.0.17 and the release.

**Comment by LovElizabeth** [comment]
> > > Try the VAE-ft-mse-840000? The VAE which is recommanded by Stablity AI.
> > 
> > 
> > sorry but I think it's not VAE got problem, whatever I turn on or turn off VAE or changed the VAE to VAE-ft-mse-840000 or another, It's just not working and console gives similar log as before.
> 
> Well, it sounds annoying, maybe disable the xformers and just enable the Scaled Dot Product cross attention optimization is better.

I'm using args --opt-sdp-attention instead of xformers, It got similarly sample speed as xformers even bit faster and fully compatible with multidiffusion-upscaler.

**Comment by LieDeath** [comment]
> > > > Try the VAE-ft-mse-840000? The VAE which is recommanded by Stablity AI.
> > > 
> > > 
> > > I was already using a model-specific VAE that prevents a lot of the black boxes. And disabling half VAE.
> > > It's not a settings thing; it's an incompatibility with newer versions of torch and xformers. No black box problems on the current versions that A1111 uses (1.13 and 0.0.16), but if you try and do any img2img with new versions, you'll get this error.
> > > (I'm not sure if it's to do with the tiled VAE or multidiffusion specifically, I'd need to check which)
> > 
> > 
> > How about using the xformers 0.0.17rc482 instead? I test and confirm that this older version is workable.
> 
> With Torch 2.0? I can't remember when xformers stopped using 1.13 and started using 2.0; it was some time between the beta versions of 0.0.17 and the release.

Yes, the 0.0.17 release is capeable with torch 2.0

**Comment by RainehDaze** [comment]
> > > > Try the VAE-ft-mse-840000? The VAE which is recommanded by Stablity AI.
> > > 
> > > 
> > > sorry but I think it's not VAE got problem, whatever I turn on or turn off VAE or changed the VAE to VAE-ft-mse-840000 or another, It's just not working and console gives similar log as before.
> > 
> > 
> > Well, it sounds annoying, maybe disable the xformers and just enable the Scaled Dot Product cross attention optimization is better.
> 
> I'm using args --opt-sdp-attention instead of xformers, It got similarly sample speed as xformers even bit faster and fully compatible with multidiffusion-upscaler.

Ah, right, one of the new 2.0 optimisations. I'll need to give that a try.

**Comment by RainehDaze** [comment]
> > > > Try the VAE-ft-mse-840000? The VAE which is recommanded by Stablity AI.
> > > 
> > > 
> > > sorry but I think it's not VAE got problem, whatever I turn on or turn off VAE or changed the VAE to VAE-ft-mse-840000 or another, It's just not working and console gives similar log as before.
> > 
> > 
> > Well, it sounds annoying, maybe disable the xformers and just enable the Scaled Dot Product cross attention optimization is better.
> 
> I'm using args --opt-sdp-attention instead of xformers, It got similarly sample speed as xformers even bit faster and fully compatible with multidiffusion-upscaler.

Works, but it uses a ton more VRAM (I'm a bit less sure if it's faster); need to lower the VRAM tiling quite a bit to make use of it. Worth noting, that.

**Comment by RainehDaze** [comment]
Unrelated to the issue solving, but having upgraded to 2.0.0 and using --opt-sdp-attention instead, I generated a 1536x1024 image in 46 seconds, which is shockingly improved over before.

**Comment by pkuliyi2015** [comment]
I update the extension to support sdp in the dev branch. After testing it will be merged to the main branch, please feel free to have a test if you want to experience it first.

**Comment by RainehDaze** [comment]
I'm not sure what that changes from the main branch (it looked like it worked from my earlier tests anyway); but it's working.

**Comment by boricuapab** [comment]
I've noticed a similar issue using txt2img, but in my case I get black upscaled images when using xformers 0.0.18

[--opt-sdp-attention ](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/135)

I reverted to xformers 0.0.17 and the black upscaled images issue is gone.

**Comment by boricuapab** [comment]
It's all working with torch 2 and xformers 0.0.20

But, if you want to change xformer version:

cd into the a1111 venv/scripts folder
click on the explorer tab and type in cmd + enter
type
activate (to activate the venv)
then type the following commands
pip uninstall xformers
pip install xformers==0.0.17
