### ISSUE TITLE
unsure what im doing wrong using a 7900xtx

### ISSUE THREAD

**Issue by MackanJ2001** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#113]
[Tiled VAE]: input_size: torch.Size([1, 4, 144, 256]), tile_size: 128, padding: 11
[Tiled VAE]: split to 1x2 = 2 tiles. Optimal tile size 128x128, original tile size 128x128
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 128 x 72 image
Error completing request
Arguments: ('task(nuo70ibzjew1646)', 'technological advancement, futuristic,(character far back:1.5), 1girl, (large field of view:1.5), full body, holding sword, chinese dress,', 'badhandv4, easynegative,(worst quality, low quality:1.4), (depth of field, blurry:1.2), (greyscale, monochrome:1.1), 3D face, cropped, lowres, text, jpeg artifacts, signature, watermark, username, blurry, artist name, trademark, watermark, title, multiple view, Reference sheet,nsfw,, (worst quality, low quality:1.4), (depth of field, blurry:1.2), (greyscale, monochrome:1.1), 3D face, cropped, lowres, text, jpeg artifacts, signature, watermark, username, blurry, artist name, trademark, watermark, title, multiple view, Reference sheet,, longbody, lowres, bad anatomy, bad hands, missing fingers, pubic hair,extra digit, fewer digits, cropped, worst quality, low quality,( showing belly:1.5),', [], 20, 0, False, False, 30, 1, 7, -1.0, -1.0, 0, 0, 0, False, 1152, 2048, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, True, 'MultiDiffusion', False, 10, 1, 1, 64, True, True, 2048, 1152, 128, 128, 64, 1, 'None', 2, False, False, False, False, False, 0, 0, 1, 1, '', '', 'Background', 0.2, -1.0, False, 0, 0, 0.6, 0.6, '', '', 'Background', 0.2, -1.0, False, 0.4, 0, 0.6, 0.6, '', '', 'Background', 0.2, -1.0, False, 0, 0.4, 0.6, 0.6, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.6, 0.6, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, True, False, True, True, True, 1024, 128, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'Refresh models', False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, 50, 0, 1, 512, 512, True, False, False, True, True, False, 1, True, 3, False, 3, False, 3, 1) {}
Traceback (most recent call last):
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\modules\processing.py", line 655, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\modules\processing.py", line 655, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\modules\processing.py", line 440, in decode_first_stage
    x = model.decode_first_stage(x)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111-main\scripts\vae_optimize.py", line 480, in __call__
    return self.vae_tile_forward(x)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111-main\scripts\vae_optimize.py", line 362, in wrapper
    ret = fn(*args, **kwargs)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111-main\scripts\vae_optimize.py", line 661, in vae_tile_forward
    if self.estimate_group_norm(downsampled_z, estimate_task_queue, color_fix=self.color_fix):
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111-main\scripts\vae_optimize.py", line 575, in estimate_group_norm
    tile = group_norm_func(tile)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111-main\scripts\vae_optimize.py", line 454, in group_norm_func
    return custom_group_norm(x, 32, mean, var, weight, bias, 1e-6)
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111-main\scripts\vae_optimize.py", line 324, in custom_group_norm
    out = F.batch_norm(input_reshaped, mean, var, weight=None, bias=None,
  File "B:\applicationer\diffusion\automatic1111\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\functional.py", line 2450, in batch_norm
    return torch.batch_norm(
RuntimeError: shape '[1, 32, 1, 1, 1]' is invalid for input of size 0

Im also sometimes getting the could not allocate tenso with "xxxx" bytes. there is nto enough gpu video memory
specs is 
7900xtx 24gb vram
3900x
32gb ram

**Comment by sorryhorizonTT** [comment]
seems like it appears only between amd users.
i have this error also "RuntimeError: shape '[1, 32, 1, 1, 1]' is invalid for input of size 0"
im 6700xt user btw
kick me if there is any solution

**Comment by wzddl** [comment]
kick me if there is any solution
我也同样有这个问题，有解决方案记得踢我

**Comment by SGKino** [comment]
Same issue here, using the RTX 4070.
"RuntimeError: shape '[2, 64, 96, 320]' is invalid for input of size 5898240"

I only got this error, when I am using some anime model like "Ghost", in img2img upscaling.
