### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by LieDeath** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#13]
Facing issue weird. 遇到了奇怪的问题。

Traceback (most recent call last):
  File "D:\AI6\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI6\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1013, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\AI6\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 911, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "D:\AI6\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1800, in preprocess
    x["name"],
TypeError: 'int' object is not subscriptable

Any ideas? 有什么建议吗？
Seems like bug with gradio app. 似乎是gradio app引起的BUG。

Launching Web UI with arguments: --api --xformers

No running, No images, only traceback it is. 没有运行，没有图片，只输出了报错。

**Comment by pkuliyi2015** [comment]
这大概率是个浏览器问题。刷新页面，重启浏览器，或者换另外一个浏览器。

**Comment by LieDeath** [comment]
> 这大概率是个浏览器问题。刷新页面，重启浏览器，或者换另外一个浏览器。

谢谢，通过git pull解决了
