### ISSUE TITLE
Out of Memory - 1207959552 bytes (1.2GB) on AMD 5700 (8 GB)

### ISSUE THREAD

**Issue by mr-september** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#134]
Running on the latest [DirectML implementation](https://github.com/lshqqytiger/stable-diffusion-webui-directml), W11.

I cannot use any part of this extension at all. I tried dropping the batch size to 1, scale factor to 1, and VAE settings to half the default. Even turning off VAE.

Confused why it claims to be unable to get 1.2GB from my 8GB GPU. In Task Manager, it shows full usage of 8GB before the webui console gives the out of memory error and halts.

EDIT: With some further testing from comments below, I can turn on Tiled VAE (without Multidiffusion). Even playing around with the tile size, it sometimes outputs grey blocks randomly.

**Comment by Miraihi** [comment]
Albeit I'm capable of using that extension (RX580 8Gb), but only technically, since it produces 2 empty grey tiles at the lower left corner every time.

**Comment by Cwieku666** [comment]
> Albeit I'm capable of using that extension (RX580 8Gb), but only technically, since it produces a group of empty grey tiles at the lower left corner every time I try to generate anything higher than 1000 p resolution.

on my RX 470 4gb vram (directml and win11) I can make for example 512x1024 or 512x2048 without grey rectangle as long as I leave Width or Height at 512 and I see in cmd that Tiled VAE is spliting it for example like this
[Tiled VAE]: split to 1x3 = 3 tiles. Optimal tile size 48x48, original tile size 48x48
but with spliting like this:
[Tiled VAE]: split to 2x3 = 6 tiles. Optimal tile size 48x32, original tile size 48x48
I'll get grey artefacts
so if you can, check if this works for you.
I even managed to make an image with a resolution of 512x4096 on my 4gb vram card: https://i.imgur.com/9m9uPe0.jpeg
settings where i managed to generate 512x2048 (it took me 5min 20 seconds) https://i.imgur.com/qI8ALn4.png

**Comment by Cwieku666** [comment]
Unfortunately with 4gb of vram, I get out of memory error if I try to change Decoder Tile Size to anything bigger than 48, but I'm glad that someone managed to get it work with other than long rosolutions like 512x1024/2048/4096

**Comment by mr-september** [comment]
I'm back, after a fresh pull, `--precision full` and `--no-half` are no longer required, so I've taken those off. However, this gives an error from tiled diffusion:

```
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\modules\img2img.py", line 172, in img2img
    processed = process_images(p)
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 655, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 655, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 440, in decode_first_stage
    x = model.decode_first_stage(x)
  File "E:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "E:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "E:\stable-diffusion-webui-directml\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py", line 400, in __call__
    return self.vae_tile_forward(x)
  File "E:\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py", line 282, in wrapper
    ret = fn(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py", line 562, in vae_tile_forward
    downsampled_z = F.interpolate(
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\functional.py", line 3929, in interpolate
    return torch._C._nn._upsample_nearest_exact2d(input, output_size, scale_factors)
RuntimeError: "compute_indices_weights_nearest" not implemented for 'Half'
```

**Comment by Miraihi** [comment]
> I'm back, after a fresh pull, `--precision full` and `--no-half` are no longer required, so I've taken those off. However, this gives an error from tiled diffusion:

I was wrong so edited my original comment. Though I indeed don't need `--precision full` anymore.

**Comment by mr-september** [comment]
Thanks! You are right, adding back `--no-half` overcomes this issue, and Tiled Diffusion functions.

**Comment by LieLieLiekey** [comment]
> 

could you share the parameter COMMANDLINE_ARGS?  i meet the same problems

MY parameter is `COMMANDLINE_ARGS  = --medvram --no-half --opt-sub-quad-attention --opt-split-attention-v1 --disable-nan-check`
