### ISSUE TITLE
Noise Inversion Fail after v1.1 update

### ISSUE THREAD

**Issue by SLAPaper** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#164]
```
Traceback (most recent call last):
  File "D:\workspace\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\workspace\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\workspace\stable-diffusion-webui\modules\img2img.py", line 181, in img2img
    processed = process_images(p)
  File "D:\workspace\stable-diffusion-webui\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "D:\workspace\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "D:\workspace\stable-diffusion-webui\modules\processing.py", line 669, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\workspace\stable-diffusion-webui\modules\processing.py", line 1115, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "D:\workspace\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 249, in wrapper
    return fn(*args, **kwargs)
  File "D:\workspace\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py", line 592, in sample_img2img
    samples = sampler.launch_sampling(t_enc + 1, lambda: sampler.func(sampler.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=sampler.callback_state, **extra_params_kwargs))
  File "D:\workspace\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 278, in launch_sampling
    return func()
  File "D:\workspace\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py", line 592, in <lambda>
    samples = sampler.launch_sampling(t_enc + 1, lambda: sampler.func(sampler.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=sampler.callback_state, **extra_params_kwargs))
  File "C:\Users\slapa\scoop\apps\miniconda3\current\envs\sd_webui_new\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\workspace\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 128, in sample_euler    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "C:\Users\slapa\scoop\apps\miniconda3\current\envs\sd_webui_new\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: CFGDenoiser.forward() missing 1 required positional argument: 's_min_uncond'
```

`CFGDenoiser` adds a new parameter that needs to be filled
![image](https://user-images.githubusercontent.com/7543632/235584052-a624f3a6-dd59-4838-988c-2c66bbfe67ff.png)

Trying to test #159 but find it report error after update.

**Comment by garettwong** [comment]
Where can we find out this script file to edit it? Thank you!

**Comment by thot-experiment** [comment]
i'm too busy to find out how to fix this properly or what the heck `s_min_uncond` is actually supposed to reference, but briefly skimming the code it seems like it defaults to zero, for a quick fix so that you don't have to roll back to a previous version you can add 's_min_uncond' and set it to zero in the extra args dict on line 585 of `tile_methods/abstractdiffusion.py` like so:

```python
        extra_args={
            'cond': conditioning, 
            'image_cond': image_conditioning, 
            'uncond': unconditional_conditioning, 
            'cond_scale': p.cfg_scale,
            's_min_uncond': 0,
        }
```

**Comment by OO-ooo-OO** [comment]
This happened to me too when trying noise inversion

**Comment by garettwong** [comment]
> i'm too busy to find out how to fix this properly or what the heck `s_min_uncond` is actually supposed to reference, but briefly skimming the code it seems like it defaults to zero, for a quick fix so that you don't have to roll back to a previous version you can add 's_min_uncond' and set it to zero in the extra args dict on line 585 of `tile_methods/abstractdiffusion.py` like so:
> 
> ```python
>         extra_args={
>             'cond': conditioning, 
>             'image_cond': image_conditioning, 
>             'uncond': unconditional_conditioning, 
>             'cond_scale': p.cfg_scale,
>             's_min_uncond': 0,
>         }
> ```
> 
> just be aware that i tracked this down in like 15 minutes and I **do not** understand the implications of just setting this to zero, it seems to work for me but it could subtly break things

it works, thanks!!!

**Comment by OO-ooo-OO** [comment]
I'm still getting the same error @Kahsolt after downloading the zip again and replacing. Is it not in the zip yet?

**Comment by Kahsolt** [comment]
@OO-ooo-OO You need also to update your sd-webui, say `git pull --rebase`. Not only update this repo.

**Comment by OO-ooo-OO** [comment]
@Kahsolt Wow you replied fast. Thank you. Sorry I think I jumped the gun. Thought reloading UI would reload the extension. I was gonna edit my comment after testing restarting webui. I get no error now. It seems stuck at 50% though but that's not related to this issue.

**Comment by slashedstar** [comment]
I had to delete "'s_min_uncond': p.s_min_uncond" because a `StableDiffusionProcessingImg2Img' object has no attribute 's_min_uncond'` error, is it because I didn't update the webui? I'm at **22bcc7b** in the webui

**Comment by pkuliyi2015** [comment]
Yes. But my personal experience shows that the latest update of webui
is relatively stable. You may try to update.

**Comment by slashedstar** [comment]
Yeah I just reverted the change and updated
