### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by halr9000** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#179]
I'm able to crash it, will work on documenting repro but here's the dump with all arguments:

```
[Tiled Diffusion] ControlNet found, support is enabled.
Error completing request
Arguments: ('task(nr0kb8n7t0sbwdh)', 'best quality, 4k, ultra realistic photo\nNegative prompt: 16-token-negative-deliberate-neg,\nSteps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 1010549515, Size: 910x512, Model hash: 6bc8f9b865, Model: sd15_visiongenRealism_visiongenRealism, Tiled Diffusion: "{\'Method\': \'MultiDiffusion\', \'Latent tile width\': 96, \'Latent tile height\': 96, \'Overlap\': 48, \'Tile batch size\': 1, \'Region control\': {\'Region 1\': {\'enable\': True, \'x\': 0.6666, \'y\': 0, \'w\': 0.3333, \'h\': 1, \'prompt\': \'ufo\', \'neg_prompt\': \'\', \'blend_mode\': \'Foreground\', \'feather_ratio\': 0, \'seed\': 243223430}, \'Region 2\': {\'enable\': True, \'x\': 0.3333, \'y\': 0, \'w\': 0.3333, \'h\': 1, \'prompt\': \'ufo\', \'neg_prompt\': \'\', \'blend_mode\': \'Foreground\', \'feather_ratio\': 0, \'seed\': 243223430}, \'Region 3\': {\'enable\': True, \'x\': 0, \'y\': 0, \'w\': 0.3333, \'h\': 1, \'prompt\': \'ufo\', \'neg_prompt\': \'\', \'blend_mode\': \'Foreground\', \'feather_ratio\': 0, \'seed\': 243223432}}}"\n\n', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 910, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, True, 'MultiDiffusion', False, 10, 1, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, True, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, True, True, True, False, 2048, 128, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', <controlnet.py.UiControlNetUnit object at 0x000001B656EB1D80>, <controlnet.py.UiControlNetUnit object at 0x000001B656EB19C0>, <controlnet.py.UiControlNetUnit object at 0x000001B656EB1690>, <controlnet.py.UiControlNetUnit object at 0x000001B656EB2800>, False, False, 'Horizontal', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "D:\hal\stable-diffusion\ux\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\hal\stable-diffusion\ux\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\hal\stable-diffusion\ux\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "D:\hal\stable-diffusion\ux\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "D:\hal\stable-diffusion\ux\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "D:\hal\stable-diffusion\ux\modules\processing.py", line 669, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\hal\stable-diffusion\ux\modules\processing.py", line 880, in sample
    self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)
  File "D:\hal\stable-diffusion\ux\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 429, in <lambda>
    sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(
  File "D:\hal\stable-diffusion\ux\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 503, in create_sampler_hijack
    delegate.init_done()
  File "D:\hal\stable-diffusion\ux\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py", line 113, in init_done
    assert self.total_bboxes > 0, "Nothing to paint! No background to draw and no custom bboxes were provided."
AssertionError: Nothing to paint! No background to draw and no custom bboxes were provided.

Processing folder: D:\hal\stable-diffusion\output\2023-05-07
[Tiled Diffusion] ControlNet found, support is enabled.
Error completing request
Arguments: ('task(24si8jgf0hmqmz9)', 'best quality, 4k, ultra realistic photo', '16-token-negative-deliberate-neg,', [], 20, 0, False, False, 1, 1, 7, 1010549515.0, -1.0, 0, 0, 0, False, 512, 910, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, True, 'MultiDiffusion', False, 10, 1, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, True, False, False, True, 0, 0, 0.3333, 1, 'ufo', '', 'Foreground', 0.2, 1010549515.0, True, 0.3333, 0, 0.3333, 1, 'ufo', '', 'Foreground', 0.2, 1010549513.0, True, 0.6666, 0, 0.3333, 1, 'ufo', '', 'Foreground', 0.2, 1010549516.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, True, True, True, False, 2048, 128, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', <controlnet.py.UiControlNetUnit object at 0x000001B657311210>, <controlnet.py.UiControlNetUnit object at 0x000001B657104820>, <controlnet.py.UiControlNetUnit object at 0x000001B657221210>, <controlnet.py.UiControlNetUnit object at 0x000001B657106620>, False, False, 'Horizontal', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "D:\hal\stable-diffusion\ux\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\hal\stable-diffusion\ux\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\hal\stable-diffusion\ux\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "D:\hal\stable-diffusion\ux\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "D:\hal\stable-diffusion\ux\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "D:\hal\stable-diffusion\ux\modules\processing.py", line 669, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\hal\stable-diffusion\ux\modules\processing.py", line 880, in sample
    self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)
  File "D:\hal\stable-diffusion\ux\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 429, in <lambda>
    sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(
  File "D:\hal\stable-diffusion\ux\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 484, in create_sampler_hijack
    sampler = self.saved_create_sampler(name, model)
  File "D:\hal\stable-diffusion\ux\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 429, in <lambda>
    sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(
  File "D:\hal\stable-diffusion\ux\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 484, in create_sampler_hijack
    sampler = self.saved_create_sampler(name, model)
  File "D:\hal\stable-diffusion\ux\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 429, in <lambda>
```

[follows 100's more of these]

then at the bottom

```
  File "D:\hal\stable-diffusion\ux\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 430, in <lambda>
    name, model, p, Method(method),
  File "C:\Users\hal\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by halr9000** [comment]
I had saved the config to try and reuse a 3-column arrangement, here's contents:

```
{
  "bbox_controls": [
    {
      "enable": true,
      "x": 0,
      "y": 0,
      "w": 0.3333,
      "h": 1,
      "prompt": "",
      "neg_prompt": "",
      "blend_mode": "Foreground",
      "feather_ratio": 0.2,
      "seed": -1
    },
    {
      "enable": true,
      "x": 0.3333,
      "y": 0,
      "w": 0.3333,
      "h": 1,
      "prompt": "",
      "neg_prompt": "",
      "blend_mode": "Foreground",
      "feather_ratio": 0.2,
      "seed": -1
    },
    {
      "enable": true,
      "x": 0.6666,
      "y": 0,
      "w": 0.3333,
      "h": 1,
      "prompt": "",
      "neg_prompt": "",
      "blend_mode": "Foreground",
      "feather_ratio": 0.2,
      "seed": -1
    }
  ]
}
```

**Comment by halr9000** [comment]
Repro steps and config

- SD UX fork, latest
- multidiffusion latest

1. restart web UI
2. set rez to 16:9 using aspect ratio helper -> 910 x 512 (wide)
3. enable tiled, enable control
4. create canvas
5. load config above (P.S. would love a drop down list of files in that folder!), message confirms it was loaded, settings look accurate (pictured)
6. observe the region canvas was not updated, it's just white (pictured)
7. generate and...

It did not throw assertion! Argh, I'll keep messing with it... Maybe the dump has the answer?

![image](https://user-images.githubusercontent.com/18482/236687032-e5d266a3-605e-43c4-89ee-051e152036bb.png)
![image](https://user-images.githubusercontent.com/18482/236687093-aed5a736-aa23-4f98-9b72-228a993f7fd3.png)

**Comment by halr9000** [comment]
Related bugs I see while trying to repro:

* loading config from file does not update canvas
* loading config from file with type=foreground, does not  show feather setting in UI. Toggling to background and back is workaround.

![image](https://user-images.githubusercontent.com/18482/236687314-545ba689-69f4-48fe-bbfd-1fc8592a628a.png)

![image](https://user-images.githubusercontent.com/18482/236687297-a3f8588a-709c-4018-8456-2215bc2adb40.png)

**Comment by Kahsolt** [comment]
This `RecursionError` is due to a recent PR, and have been removed in the lastest commit of this repo.
You should not find this line 484 `sampler = self.saved_create_sampler(name, model)` in your code :(
Please check the latest commit with `git pull --rebase`

**Comment by Kahsolt** [comment]
For the config file, why the seed are all `-1`, this means seed for each region is independently randomly chosen, you wants to test the identity... right? 🤔

PS: What I meant the value precision is not about the config values on the control panel, but the computed tensor values. I'll follow your experiment and find why.

**Comment by Kahsolt** [comment]
As for the UI responsibility... the sd-webui framework is developed based on the shitty `gradio`, its functionality somewhat incomplete, not all actions will behave ideally responsible to end users :(

**Comment by Kahsolt** [comment]
Now, hit the config load button **twice**, your canvas should be updated.

Why twice? God knows...

**Comment by halr9000** [comment]
> For the config file, why the seed are all `-1`, this means seed for each region is independently randomly chosen, you wants to test the identity... right? 🤔

Yeah that was just me trying to reduce variables in the attempt to repro.

**Comment by halr9000** [comment]
> Now, hit the config load button **twice**, your canvas should be updated.
> 
> Why twice? God knows...

Some other extension authors have found a way to manipulate the controls on same page. Have you looked at the preset config or aspect ratio, or Deforum by chance? There's several with the same sort of workflow that's similar to your use case:

- complicated settings, need to reduce repetitive steps
- ability to save & load configuration settings to a file
- loading configuration settings will update settings in the active UI window

**Comment by pkuliyi2015** [comment]
I want to clarify that the twice click is a recent gradio bug. Before 3.21.0 the two bugs you mentioned:

> * loading config from file does not update canvas
> * loading config from file with type=foreground, does not  show feather setting in UI. Toggling to background and back is workaround.

doesn't exists. In recent updates (>=3.21.0) the gradio accordion delete the DOM contents when a accordion is closed. Hence, this also deleted all event listeners inside the accordion. I clearly know the bug, but I don't have anyway to fix it.

Luckily, the gradio bug is fixed yesterday in this [PR](https://github.com/gradio-app/gradio/pull/4073). So you just need to wait for the next gradio release & update.

No need for more test.

**Comment by halr9000** [comment]
Note to self: no need to second guess @pkuliyi2015 , he knows what he's about ;)
