### ISSUE TITLE
it report some error  when I use it？

### ISSUE THREAD

**Issue by wolfyangfeng** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#18]
Sorry but when I try them in t2i or i2i (defalut settings)，it always report" RuntimeError: Cannot set version_counter for inference tensor", is any mistake I have made ?

I haven't enable the controlnet when I use multdiffusion and tlied VAE.

**ERROR REPORT:**

_Traceback (most recent call last):
  File "H:\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "H:\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "H:\stable-diffusion-webui-directml\modules\img2img.py", line 171, in img2img
    processed = process_images(p)
  File "H:\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "H:\stable-diffusion-webui-directml\modules\processing.py", line 577, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "H:\stable-diffusion-webui-directml\modules\processing.py", line 1017, in init
    self.init_latent = self.sd_model.get_first_stage_encoding(self.sd_model.encode_first_stage(image))
  File "H:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "H:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "H:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "H:\stable-diffusion-webui-directml\modules\lowvram.py", line 48, in first_stage_model_encode_wrap
    return first_stage_model_encode(x)
  File "H:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 83, in encode
    h = self.encoder(x)
  File "H:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py", line 481, in __call__
    return self.vae_tile_forward(x)
  File "H:\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py", line 369, in wrapper
    ret = fn(*args, **kwargs)
  File "H:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\stable-diffusion-webui-directml\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py", line 627, in vae_tile_forward
    tile = z[:, :, input_bbox[2]:input_bbox[3],
RuntimeError: Cannot set version_counter for inference tensor_

**Comment by lyp150213** [comment]
I also encountered this problem，My graphics card is AMD

**Comment by qwerkilo** [comment]
不要设置vae到gpu，我用amd，如果打开了vae到gpu我也收到这个错误信息。不设置vae到gpu可以工作但生成的图有一小块色块
