### ISSUE TITLE
Why doesn't Tiled VAE work for me?

### ISSUE THREAD

**Issue by LLKoder** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#181]
I confused, may be I'm wrong or maybe it's Tiled VAE's bug.

I have RTX 3070, 8 GB VRAM and I wanna get resolution 2048x2048.

What I do:

![2023-05-08_15-46](https://user-images.githubusercontent.com/50442676/236748324-28e31621-d5a1-45b0-a9de-5988676e6e37.png)

Or:

![2023-05-08_15-47](https://user-images.githubusercontent.com/50442676/236748378-358b8275-4811-4ee1-8ab0-117186ca4e35.png)

BTW, I get some resolution without Tiled VAE. IMHO It's max resolution that I allow myself.

![2023-05-08_15-50](https://user-images.githubusercontent.com/50442676/236748555-5f1b530b-38cd-4a60-9c20-e183eeb9e6d7.png)

What am I doing wrong? Or is it really a bug?

**Comment by Kahsolt** [comment]
Generally 8G vram should allow `tile_size=96` for decoding...
Please screenshot on the console logs, it is more detailed and helps us to locate the real issue.

**Comment by LLKoder** [comment]
@Kahsolt,

I have tried to minimize all sizes of Tile Size and I have gotten the same issue.

![2023-05-08_19-52](https://user-images.githubusercontent.com/50442676/236817477-942b0eb0-0614-4130-8fc7-40933d4a7c69.png)
```
To create a public link, set `share=True` in `launch()`.
Startup time: 23.6s (import torch: 4.2s, import gradio: 0.9s, import ldm: 0.5s, other imports: 1.1s, load scripts: 4.0s, load SD checkpoint: 6.8s, create ui: 5.7s, gradio launch: 0.3s).
  0%|                                                                                           | 0/20 [00:02<?, ?it/s]
Error completing request
Arguments: ('task(f61ryv58kmhrsv8)', '1girl, ', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 2048, 2048, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, 'MultiDiffusion', False, 10, 1, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, True, True, True, True, False, 256, 48, False, '', 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', <controlnet.py.UiControlNetUnit object at 0x00000219FF4281F0>, <controlnet.py.UiControlNetUnit object at 0x00000219FF429D80>, <controlnet.py.UiControlNetUnit object at 0x00000219FEFDDE70>, <controlnet.py.UiControlNetUnit object at 0x00000219FF429F30>, <controlnet.py.UiControlNetUnit object at 0x00000219FF428D00>, False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Bilinear', False, 'Lerp', '', '', False, False, None, True, False, None, None, '', '', '', '', 'Auto rename', {'label': 'Upload avatars config'}, 'Open outputs directory', 'Export to WebUI style', True, {'label': 'Presets'}, {'label': 'QC preview'}, '', [], 'Select', 'QC scan', 'Show pics', None, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, False, False, '#000000', False, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', None, False, None, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "C:\Users\test\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\test\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Users\test\stable-diffusion-webui\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "C:\Users\test\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\modules\processing.py", line 669, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\Users\test\stable-diffusion-webui\modules\processing.py", line 887, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\Users\test\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 377, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Users\test\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 251, in launch_sampling
    return func()
  File "C:\Users\test\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 377, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\Users\kakus\AI\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\kakus\AI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 135, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "C:\Users\kakus\AI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Users\test\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\test\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\kakus\AI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Users\kakus\AI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "C:\Users\kakus\AI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "C:\Users\kakus\AI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "C:\Users\kakus\AI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "C:\Users\test\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\Users\kakus\AI\.venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\test\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\Users\test\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 272, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "C:\Users\kakus\AI\.venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\test\stable-diffusion-webui\modules\sd_hijack_optimizations.py", line 121, in split_cross_attention_forward
    raise RuntimeError(f'Not enough memory, use lower resolution (max approx. {max_res}x{max_res}). '
RuntimeError: Not enough memory, use lower resolution (max approx. 1472x1472). Need: 6.0GB free, Have:3.1GB free
```

**Comment by pkuliyi2015** [comment]
According to your logs, the problem is not from the Tiled VAE but from the UNet. And the OOM happens on the attention mechanism.

One effective solution is to use --xformers command line when start up. If you don't know what's this and how to do, just search and there will be many tutorials on this.

If you confirm you have used the xformers but the OOM still happen, your logs should change, and, please post your log here again.

**Comment by LLKoder** [comment]
Thanks, this solution helped me with this issue.

**Comment by LLKoder** [comment]
It may be need to include this information in the README.md install or run sections so that users can use the extension out of the box.

**Comment by Kahsolt** [comment]
> It may be need to include this information in the README.md install or run sections so that users can use the extension out of the box.

A brief description for all tunable extra parameters is planned :)
