### ISSUE TITLE
error when using IMG2IMG

### ISSUE THREAD

**Issue by alenknight** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#190]
I'm getting the following error when i send to img2img and try to run multidiffusion - 

MultiDiffusion hooked into 'Euler a' sampler, Tile size: 96x96, Tile batches: 1, Batch size: 4. (ext: RegionCtrl, ContrlNet)
Error running process_batch: C:\AI\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 435, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "C:\AI\stable-diffusion-webui\extensions\sd-dynamic-thresholding\scripts\dynamic_thresholding.py", line 127, in process_batch
    p.sampler = sd_samplers.create_sampler(fixed_sampler_name, p.sd_model)
  File "C:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 364, in <lambda>
    sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(
  File "C:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 434, in create_sampler_hijack
    sampler = sd_samplers.create_sampler_original_md(name, model)
AttributeError: module 'modules.sd_samplers' has no attribute 'create_sampler_original_md'

screenshot of the extensions i'm running
![Screenshot 2023-05-11 at 10 32 56 PM](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/22153900/a795b12e-77c1-498d-bdb9-035f9bb2bf25)

also :  python: 3.10.9  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.28.1  •  commit: [5ab7f213]

**Comment by Kahsolt** [comment]
This seems another example of webui scripts execution order....
The `sd-dynamic-thresholding` and `tiled-diff` both hijacks `sd_samplers.create_sampler`, so there's may be call order or compatible problem.

Need time to investigate.
see also #186

**Comment by alenknight** [comment]
> This seems another example of webui scripts execution order.... The `sd-dynamic-thresholding` and `tiled-diff` both hijacks `sd_samplers.create_sampler`, so there's may be call order or compatible problem.
> 
> Need time to investigate. see also #186

thanks for the insight... that put me onto some testing if it helps.  

- [ ] If I pick ‘tiled diffusion’ or ‘dynamic threshold’ …. either/or causes the error in img2img
- [ ] Running Ultimate SD Upscaler with tiling doesn’t seem to trigger the error (disabled tiled diffusion).. works in conjunction with dynamic threshold….(possible temporary workaround, but lose some features multi tile diffusion brings)
- [ ] Running the tiled option checkbox at the top also doesn’t seem to trigger the error. (you know the default SD tiled checkbox that creates tiled surface art)
- [ ] Txt2img seems to work fine with both… likely it’s not doing the same tiling, so it’s not calling the files?
- [ ] Running region prompt control in img2img… still throws the error… and also won’t work (likely whole module blown )
- [ ] If I uncheck one of the two… and enable the other one…. That one starts working.  (Releasing the files)

**Comment by PotatoBananaApple** [comment]
I have been using dynamic threshold with tiled diffusion in img2img and it has been working. I started testing noise inversion today and noticed dynamic threshold does not work when noise inversion enabled. I don't get any errors though. I don't have the latest versions. Don't know exactly what has changed after them.

Multidiffusion: `f54a8fc5`
Dynamic threshold: `5d3465c4`

**Comment by alenknight** [comment]
> I have been using dynamic threshold with tiled diffusion in img2img and it has been working. I started testing noise inversion today and noticed dynamic threshold does not work when noise inversion enabled. I don't get any errors though. I don't have the latest versions. Don't know exactly what has changed after them.
> 
> Multidiffusion: `f54a8fc5` Dynamic threshold: `5d3465c4`

these *may* be related.... but i think this might need to be a separate issue (though it's possible it's similar seizing of the files as @Kahsolt  suggested).... still, might wanna open a ticket for that

**Comment by alenknight** [comment]
@Kahsolt / @pkuliyi2015  - i did some more testing... some interesting results  :
- first the boring one.  tried all manner of optimizers... no difference.  expected behavior 
- here's the fun one : if i leave the A1111 browser window open..... the one that caused the errors with BOTH tile diffusion and dynamic threshold ----. and just rerun a prompt with both on... it's working.  no error... and i then i can turn off and on either of them and they can work together.  no error, and i'm seeing they both take effect!

if i close the browser and open a new one... then the error comes back.

so... that's kinda a workaround for now... ?

**Comment by rehvka** [comment]
anyone find a permanent solution to this? I'm still struggling with it :(

**Comment by pkuliyi2015** [comment]
Thanks for bringing it to my attention. I'm busy right now and will check it carefully in my spare time.

**Comment by PotatoBananaApple** [comment]
Updated after long time, now i am stuck with this issue too 😞

**Comment by FireHaoSky** [comment]
> 



> 谢谢你让我注意到它。我现在很忙，有空的时候会仔细查看。

大佬解决了嘛？

**Comment by hananyakampa** [comment]
did anyone fins solution?

**Comment by gillopillo** [comment]
same issue here, just updated and it started happening. i am trying to use 4x-Ultrasharp as an upscaler.

**Comment by Threnos** [comment]
Bump
