### ISSUE TITLE
[Error] Region Prompt Control: UnboundLocalError: local variable 'image_cond' referenced before assignment

### ISSUE THREAD

**Issue by sadume** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#210]
When I enable region prompt control i get the following error:
`UnboundLocalError: local variable 'image_cond' referenced before assignment`

I am using default settings tiled vae disabled, tiled diffusion enabled and seems to be working

I get the same error with img2img and text2img, I tried changing many settings to see if there was conflict but nothing made any difference. I also disabled 'latent couple' extension but didn't fix the issue. Enabling tiled VAE didn't fix the issue.

Not sure what else to try.

**Comment by sadume** [comment]
`[Tiled Diffusion] ControlNet found, support is enabled.









MultiDiffusion Sampling:   0%|                           | 0/90 [00:00<?, ?it/s]MultiDiffusion hooked into 'Euler a' sampler, Tile size: 96x96, Tile batches: 1, Batch size: 4. (ext: RegionCtrl, ContrlNet)










  0%|                                                    | 0/30 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(yj25yinbqppxh1u)', '', '', [], 30, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 1024, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, True, True, False, True, 0, 0, 1, 1, 'beach with forest edge', 'buildings, people', 'Background', 0.2, -1.0, True, 0.6784, 0.1446, 0.3054, 0.8041, 'beach girl, sun hat, facing towards', '', 'Foreground', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True, True, True, False, <controlnet.py.UiControlNetUnit object at 0x7f0aa83bdc00>, <controlnet.py.UiControlNetUnit object at 0x7f0aa83bd810>, <controlnet.py.UiControlNetUnit object at 0x7f0aa99d8730>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "/workspace/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 526, in process_images
    res = process_images_inner(p)
  File "/workspace/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 680, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 907, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 377, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 251, in launch_sampling
    return func()
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 377, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/sd/stablediffusion/src/k-diffusion/k_diffusion/sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 135, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_utils/utils.py", line 243, in wrapper
    return fn(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/multidiffusion.py", line 103, in kdiff_forward
    return self.sample_one_step(x_in, org_func, repeat_func, custom_func)
  File "/workspace/sd/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/multidiffusion.py", line 212, in sample_one_step
    x_tile_out = custom_func(x_tile, bbox_id, bbox)
  File "/workspace/sd/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/multidiffusion.py", line 101, in custom_func
    return self.kdiff_custom_forward(x, sigma_in, cond, bbox_id, bbox, self.sampler_forward)
  File "/workspace/sd/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_utils/utils.py", line 243, in wrapper
    return fn(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/abstractdiffusion.py", line 237, in kdiff_custom_forward
    tensor, uncond, image_cond_in = self.reconstruct_custom_cond(original_cond, bbox.cond, bbox.uncond, bbox)
  File "/workspace/sd/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_utils/utils.py", line 243, in wrapper
    return fn(*args, **kwargs)
  File "/workspace/sd/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/abstractdiffusion.py", line 205, in reconstruct_custom_cond
    if image_cond.shape[2:] == (self.h, self.w):    # img2img
UnboundLocalError: local variable 'image_cond' referenced before assignment
`

**Comment by sadume** [comment]
@pkuliyi2015 I reinstalled from git url but still getting the same error

**Comment by pkuliyi2015** [comment]
Please just delete the extension and install again, And then restart your webui. This is a typical cache error.
