### ISSUE TITLE
TypeError when trying to load custom config file

### ISSUE THREAD

**Issue by halr9000** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#223]
I've done this before many times, so this seems like a regression to me.

Steps:

1. Enable control
2. Create new canvas
3. type saved config filename, eg "config.json", press Load
4. Nothing happens in UI. Console shows below error.

Console output:

```
Traceback (most recent call last):
  File "D:\hal\stable-diffusion\ux\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\hal\stable-diffusion\ux\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "D:\hal\stable-diffusion\ux\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\hal\stable-diffusion\ux\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\hal\stable-diffusion\ux\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\hal\stable-diffusion\ux\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\hal\stable-diffusion\ux\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 554, in load_regions
    fp = CFG_PATH / cfg_name
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

**Comment by sebaxakerhtc** [comment]
Same here
Started from [here](https://github.com/vladmandic/automatic/issues/1182) and then after [this PR](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/pull/221) it fails

**Comment by pkuliyi2015** [comment]
Fixed with thanks.

**Comment by halr9000** [comment]
Side note -- I love OSS! I'm over here using [the ux fork](https://github.com/anapnoe/stable-diffusion-webui-ux), someone else is using Vlad's, and we're all talking about the same thing and the author can make one fix for a1111 and the rest benefit.
