### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dherorunner** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#24]
Why this error occurs？

**Comment by pkuliyi2015** [comment]
Please offer detailed screenshot, normally such kind of errors can be addressed by restart your browser.

**Comment by Zxis233** [comment]
`MultiDiffusion hooked into Euler a sampler. Tile size: 64 x 64 Tile batches: 28 Batch size: 1
  0%|                                                                       | 0/20 [00:00<?, ?it/s]
Error completing request   0%|                                             | 0/560 [00:00<?, ?it/s]
Arguments: ('task(01c8lwdq0vg6mr5)', 'Pink hair and eyes，{best quality}, {{masterpiece}}, {highres}, original, extremely detailed 8K wallpaper, 1girl, {an extremely delicate and beautiful},straight-on,upper body,foreshortening,backlighting,starry sky ,loli,curly_hair,staring,sitting,arm support,ribbed sweater,small_breasts, ((masterpiece)), (((best quality))),((ultra-detailed)), ((illustration)),((disheveled hair)), cute, depth of field, ray tracing, reflection, ((solo)), (((blue eyes))), cold face', 'easynegative,extra fingers, fewer fingers, bad anatomy', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 1080, 1920, False, 0.7, 2, 'Latent', 0, 0, 0, 0, True, False, 1024, 1024, True, 64, 64, 32, 1, 'None', 2, False, True, False, True, True, 0, 960, 64, False, False, False, False, '', 1, '', 0, '', True, False, False, 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
    processed = process_images(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 476, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 614, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "F:\stable-diffusion-webui\modules\processing.py", line 809, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 544, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 447, in launch_sampling
    return func()
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 544, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 337, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 202, in kdiff_repeat
    return self.compute_x_tile(x_in, func)
  File "F:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 288, in compute_x_tile
    single_batch_tensors = self.control_tensor_batch[batch_id]
IndexError: list index out of range

MultiDiffusion Sampling:   0%|                                             | 0/560 [01:39<?, ?it/s]
MultiDiffusion hooked into Euler a sampler. Tile size: 64 x 64 Tile batches: 28 Batch size: 1
  0%|                                                                       | 0/20 [00:00<?, ?it/s]
Error completing request   0%|                                             | 0/560 [00:00<?, ?it/s]
Arguments: ('task(7vmb3wkaii8owbc)', 'Pink hair and eyes，{best quality}, {{masterpiece}}, {highres}, original, extremely detailed 8K wallpaper, 1girl, {an extremely delicate and beautiful},straight-on,upper body,foreshortening,backlighting,starry sky ,loli,curly_hair,staring,sitting,arm support,ribbed sweater,small_breasts, ((masterpiece)), (((best quality))),((ultra-detailed)), ((illustration)),((disheveled hair)), cute, depth of field, ray tracing, reflection, ((solo)), (((blue eyes))), cold face', 'easynegative,extra fingers, fewer fingers, bad anatomy', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 1080, 1920, False, 0.7, 2, 'Latent', 0, 0, 0, 0, True, False, 1024, 1024, True, 64, 64, 32, 1, 'None', 2, False, True, True, True, True, 0, 960, 64, False, False, False, False, '', 1, '', 0, '', True, False, False, 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
    processed = process_images(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 476, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 614, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "F:\stable-diffusion-webui\modules\processing.py", line 809, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 544, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 447, in launch_sampling
    return func()
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 544, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 337, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 202, in kdiff_repeat
    return self.compute_x_tile(x_in, func)
  File "F:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 288, in compute_x_tile
    single_batch_tensors = self.control_tensor_batch[batch_id]
IndexError: list index out of range

MultiDiffusion Sampling:   0%|                                             | 0/560 [00:20<?, ?it/s]
MultiDiffusion hooked into DPM++ 2S a Karras sampler. Tile size: 64 x 64 Tile batches: 28 Batch size: 1
  0%|                                                                       | 0/20 [00:00<?, ?it/s]
Error completing request   0%|                                             | 0/560 [00:00<?, ?it/s]
Arguments: ('task(s3rzrbmn7vzlqon)', 'Pink hair and eyes，{best quality}, {{masterpiece}}, {highres}, original, extremely detailed 8K wallpaper, 1girl, {an extremely delicate and beautiful},straight-on,upper body,foreshortening,backlighting,starry sky ,loli,curly_hair,staring,sitting,arm support,ribbed sweater,small_breasts, ((masterpiece)), (((best quality))),((ultra-detailed)), ((illustration)),((disheveled hair)), cute, depth of field, ray tracing, reflection, ((solo)), (((blue eyes))), cold face', 'easynegative,extra fingers, fewer fingers, bad anatomy', [], 20, 14, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 1080, 1920, False, 0.7, 2, 'Latent', 0, 0, 0, 0, True, False, 1024, 1024, True, 64, 64, 32, 1, 'None', 2, False, True, False, True, True, 0, 960, 64, False, False, False, False, '', 1, '', 0, '', True, False, False, 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
    processed = process_images(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 476, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 614, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "F:\stable-diffusion-webui\modules\processing.py", line 809, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 544, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 447, in launch_sampling
    return func()
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 544, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 518, in sample_dpmpp_2s_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 337, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 202, in kdiff_repeat
    return self.compute_x_tile(x_in, func)
  File "F:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 288, in compute_x_tile
    single_batch_tensors = self.control_tensor_batch[batch_id]
IndexError: list index out of range

MultiDiffusion Sampling:   0%|                                             | 0/560 [01:27<?, ?it/s]
MultiDiffusion hooked into DPM++ 2S a Karras sampler. Tile size: 64 x 64 Tile batches: 4 Batch size: 8
  0%|                                                                       | 0/20 [00:00<?, ?it/s]
Error completing request   0%|                                              | 0/80 [00:00<?, ?it/s]
Arguments: ('task(ln4kbqsz43jt7kn)', 'Pink hair and eyes，{best quality}, {{masterpiece}}, {highres}, original, extremely detailed 8K wallpaper, 1girl, {an extremely delicate and beautiful},straight-on,upper body,foreshortening,backlighting,starry sky ,loli,curly_hair,staring,sitting,arm support,ribbed sweater,small_breasts, ((masterpiece)), (((best quality))),((ultra-detailed)), ((illustration)),((disheveled hair)), cute, depth of field, ray tracing, reflection, ((solo)), (((blue eyes))), cold face', 'easynegative,extra fingers, fewer fingers, bad anatomy', [], 20, 14, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 1080, 1920, False, 0.7, 2, 'Latent', 0, 0, 0, 0, True, False, 1024, 1024, True, 64, 64, 32, 8, 'None', 2, False, True, False, True, True, 0, 256, 64, False, False, False, False, '', 1, '', 0, '', True, False, False, 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui\modules\txt2img.py", line 52, in txt2img
    processed = process_images(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 476, in process_images
    res = process_images_inner(p)
  File "F:\stable-diffusion-webui\modules\processing.py", line 614, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "F:\stable-diffusion-webui\modules\processing.py", line 809, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 544, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 447, in launch_sampling
    return func()
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 544, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 518, in sample_dpmpp_2s_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\modules\sd_samplers.py", line 337, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "E:\Anaconda3\envs\MyFirstDeeplearning\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 202, in kdiff_repeat
    return self.compute_x_tile(x_in, func)
  File "F:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 288, in compute_x_tile
    single_batch_tensors = self.control_tensor_batch[batch_id]
IndexError: list index out of range
`

**Comment by LightChaser666** [comment]
I spotted the error and fixed it now. Please try again.

**Comment by dherorunner** [comment]
I don't know where the problem is, but after updating the webui today and reinstalling the extension, the problem disappeared.
I have ruled out some possibilities like checkpoint and half precision
