### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Alalajiyh** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#25]
Upscaling image with BSRGAN...
LoRA weight_unet: 0.3, weight_tenc: 0.3, model: ligneClaireStyleCogecha_v10(21e170a9ba68)
dimension: 64, alpha: 64.0, multiplier_unet: 0.3, multiplier_tenc: 0.3
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
original forward/weights is backed up.
enable LoRA for text encoder
enable LoRA for U-Net
shapes for 0 weights are converted.
LoRA model ligneClaireStyleCogecha_v10(21e170a9ba68) loaded: <All keys matched successfully>
LoRA weight_unet: 1, weight_tenc: 1, model: makotoShinkaiSubstyles_offset(ca429a1460f9)
dimension: 128, alpha: 128.0, multiplier_unet: 1, multiplier_tenc: 1
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
shapes for 0 weights are converted.
LoRA model makotoShinkaiSubstyles_offset(ca429a1460f9) loaded: <All keys matched successfully>
setting (or sd model) changed. new networks created.
MultiDiffusion hooked into DPM++ 2M Karras sampler. Tile size: 64 x 64 Tile batches: 28 Batch size: 1
[Tiled VAE]: input_size: torch.Size([1, 3, 1056, 1920]), tile_size: 960, padding: 32
[Tiled VAE]: split to 2x2 = 4 tiles. Optimal tile size 928x512, original tile size 960x960
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 960 x 528 image
[Tiled VAE]: Executing Encoder Task Queue: 100%|█████████████████████████████████████| 364/364 [00:07<00:00, 46.05it/s]
[Tiled VAE]: Done in 11.656s, max VRAM alloc 4130.609 MB
  0%|                                                                                           | 0/13 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(908z6j5sctakndi)', 0, '1girl,upper body, (close up:0.4),cool colors', '(worst quality, low quality:1.4), watermark, logo,easynegative,', [], <PIL.Image.Image image mode=RGBA size=480x264 at 0x2627F5622C0>, None, None, None, None, None, None, 20, 15, 4, 0, 1, False, False, 1, 1, 6, 1.5, 0.6, 3987989009.0, -1.0, 0, 0, 0, False, 270, 480, 0, 0, 32, 0, '', '', '', [], 0, True, False, 1024, 1024, True, 64, 64, 32, 1, 'BSRGAN', 4, False, True, True, True, True, 0, 960, 64, True, False, 'LoRA', 'ligneClaireStyleCogecha_v10(21e170a9ba68)', 0.3, 0.3, 'LoRA', 'None', 0, 0, 'LoRA', 'makotoShinkaiSubstyles_offset(ca429a1460f9)', 1, 1, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'Refresh models', '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\webui\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\webui\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\webui\stable-diffusion-webui\modules\img2img.py", line 171, in img2img
    processed = process_images(p)
  File "C:\webui\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\webui\stable-diffusion-webui\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\webui\stable-diffusion-webui\modules\processing.py", line 1048, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "C:\webui\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 322, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\webui\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "C:\webui\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 322, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\webui\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\webui\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\webui\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 123, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": [cond_in[a:b]], "c_concat": [image_cond_in[a:b]]})
  File "C:\webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\webui\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 202, in kdiff_repeat
    return self.compute_x_tile(x_in, func)
  File "C:\webui\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\multidiffusion.py", line 289, in compute_x_tile
    single_batch_tensors = self.control_tensor_batch[batch_id]
IndexError: list index out of range

**Comment by LightChaser666** [comment]
I spotted the error and fixed it now. Please try again.
