### ISSUE TITLE
AMD显卡是否支持multidiffusion

### ISSUE THREAD

**Issue by YoungGXY** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#262]
AMD RX6800XT 16G
报错显示RuntimeError: "compute_indices_weights_nearest" not implemented for 'Half'

**Comment by YoungGXY** [comment]
大佬们有没解决办法，还是说这个插件只有N卡可用

**Comment by YoungGXY** [comment]
只勾选分块扩散没有问题，问题好像是分块VAE

**Comment by YoungGXY** [comment]
只勾选启动分块VAE，不勾选快速编码器，启动结果如下
[Tiled VAE]: input_size: torch.Size([1, 3, 540, 960]), tile_size: 512, padding: 32
[Tiled VAE]: split to 1x2 = 2 tiles. Optimal tile size 448x480, original tile size 512x512
[Tiled VAE] Warning: Unknown attention optimization method . Please try to update the extension.
[Tiled VAE]: Executing Encoder Task Queue: 100%|█████████████████████████████████████████████████████████████████████| 182/182 [00:05<00:00, 35.61it/s]
[Tiled VAE]: Done in 6.128s
Error completing request
Arguments: ('task(gd0y3abmuarcppd)', 0, ' (masterpiece, best quality, ultra-detailed, best shadow), (detailed background,dark fantasy),  high contrast, (best illumination, an extremely delicate and beautiful), ((cinematic light)), colorful, hyper detail, dramatic light, intricate details, (1 girl, solo,light blue hair,  hair, sharp face,low twintails,light blue eyes, hair between eyes,dynamic angle), swirling black light around the character,black light particles,(broken glass),magic circle,Holding a samurai sword,(Kamisato Ayaka:1.9)，（（white Samurai clothing）），（red Hair knot：1.5），(Neat bangs：1.5）,Tropical rainforests, lush plants, tropical plants, vines, colorful mushrooms, grass, flowering plants, water currents, waterfalls, green water, and large lakes ', '(worst quality,low quality:1.4), monochrome, zombie,(twintails:1.3),EasyNegative, bad_prompt_version2, (worst quality:1.4), (low quality:1.4), (normal quality:1.4), lowres, skin spots, acnes, skin blemishes, age spot, glans,extra fingers, fewer fingers,strange fingers,((bad hand)),Hand grip,(lean),Extra ears,(Four ears),Strange eyes,(three arms),Many hands,(Many arms),((watermarking))', [], <PIL.Image.Image image mode=RGBA size=960x536 at 0x1E1D9863670>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 0, 540, 960, 1, 0, 0, 32, 0, '', '', '', [], 0, False, 'MultiDiffusion', False, True, 1024, 1024, 160, 144, 84, 2, 'None', 3, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, True, 512, 64, True, False, False, False, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001E1D98633D0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001E1D9860370>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001E1D98601C0>, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, 1.6, 0.97, 0.4, 0.15, 20, 0, 0, '', None, None, False, None, None, False, None, None, False, 50) {}
Traceback (most recent call last):
  File "F:\AI\stable-diffusion-webui\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "F:\AI\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\AI\stable-diffusion-webui\modules\img2img.py", line 178, in img2img
    processed = process_images(p)
  File "F:\AI\stable-diffusion-webui\modules\processing.py", line 611, in process_images
    res = process_images_inner(p)
  File "F:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "F:\AI\stable-diffusion-webui\modules\processing.py", line 671, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "F:\AI\stable-diffusion-webui\modules\processing.py", line 1236, in init
    self.init_latent = self.sd_model.get_first_stage_encoding(self.sd_model.encode_first_stage(image))
  File "F:\AI\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "F:\AI\stable-diffusion-webui\modules\sd_hijack_utils.py", line 26, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "F:\AI\stable-diffusion-webui\modules\sd_hijack_unet.py", line 76, in <lambda>
    first_stage_sub = lambda orig_func, self, x, **kwargs: orig_func(self, x.to(devices.dtype_vae), **kwargs)
  File "F:\AI\stable-diffusion-webui\Python3.10\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\AI\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 830, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "F:\AI\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 84, in encode
    moments = self.quant_conv(h)
  File "F:\AI\stable-diffusion-webui\Python3.10\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\AI\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 415, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "F:\AI\stable-diffusion-webui\extensions\a1111-sd-webui-lycoris\lycoris.py", line 751, in lyco_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lyco(self, input)
  File "F:\AI\stable-diffusion-webui\Python3.10\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "F:\AI\stable-diffusion-webui\Python3.10\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "F:\AI\stable-diffusion-webui\modules\dml\amp\autocast_mode.py", line 32, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: pre_forward(op, args, kwargs))
  File "F:\AI\stable-diffusion-webui\modules\dml\amp\autocast_mode.py", line 9, in pre_forward
    return forward(*args, **kwargs)
RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same

**Comment by tjzoo111** [comment]
RX580  4G  没任何问题    debian11   rocm5.4.3   torch2.1.0
