### ISSUE TITLE
After newest Automatic1111 update: FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\AI\\Automatic1111\\stable-diffusion-webui\\extensions\\multidiffusion-upscaler-for-automatic1111-main\\.git'

### ISSUE THREAD

**Issue by OO-ooo-OO** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#281]
After newest Automatic1111 update: FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\AI\\Automatic1111\\stable-diffusion-webui\\extensions\\multidiffusion-upscaler-for-automatic1111-main\\.git'

Traceback (most recent call last):
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\AI\Automatic1111\stable-diffusion-webui\modules\ui_extensions.py", line 157, in extension_table
    ext.read_info_from_repo()
  File "C:\AI\Automatic1111\stable-diffusion-webui\modules\extensions.py", line 60, in read_info_from_repo
    d = cache.cached_data_for_file('extensions-git', self.name, os.path.join(self.path, ".git"), read_from_repo)
  File "C:\AI\Automatic1111\stable-diffusion-webui\modules\cache.py", line 102, in cached_data_for_file
    ondisk_mtime = os.path.getmtime(filename)
  File "C:\Users\O\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\AI\\Automatic1111\\stable-diffusion-webui\\extensions\\multidiffusion-upscaler-for-automatic1111-main\\.git'
Traceback (most recent call last):
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\AI\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\AI\Automatic1111\stable-diffusion-webui\modules\ui_extensions.py", line 195, in update_config_states_table
    config_state = config_states.get_config()
  File "C:\AI\Automatic1111\stable-diffusion-webui\modules\config_states.py", line 105, in get_config
    ext_config = get_extension_config()
  File "C:\AI\Automatic1111\stable-diffusion-webui\modules\config_states.py", line 83, in get_extension_config
    ext.read_info_from_repo()
  File "C:\AI\Automatic1111\stable-diffusion-webui\modules\extensions.py", line 60, in read_info_from_repo
    d = cache.cached_data_for_file('extensions-git', self.name, os.path.join(self.path, ".git"), read_from_repo)
  File "C:\AI\Automatic1111\stable-diffusion-webui\modules\cache.py", line 102, in cached_data_for_file
    ondisk_mtime = os.path.getmtime(filename)
  File "C:\Users\O\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\AI\\Automatic1111\\stable-diffusion-webui\\extensions\\multidiffusion-upscaler-for-automatic1111-main\\.git'

**Comment by serjj39** [comment]
Та же проблема. На вкладке расширения идет бесконечный поиск установленных программ. Программы не отображаются.
При попытке обновления выскакивает ошибка как и при каждом запуске SD webui:
FileNotFoundError: [WinError 2] Не удается найти указанный файл: 'C:\\Games\\stable-diffusion-portable-main\\stable-diffusion-portable-main\\extensions\\sd-webui-controlnet-main\\.git'

**Comment by Kahsolt** [comment]
That update seems to break git track, though do not know why.
But the solution is simple: delete this extension folder and reinstall it.
