### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 512 but got size 256 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by LightningK** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#285]
在colab上部署的，图生图时遇到以下报错：
 Traceback (most recent call last):
      File "/content/microsoftexcel/modules/call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "/content/microsoftexcel/modules/call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "/content/microsoftexcel/modules/img2img.py", line 198, in img2img
        processed = process_images(p)
      File "/content/microsoftexcel/modules/processing.py", line 620, in process_images
        res = process_images_inner(p)
      File "/content/microsoftexcel/extensions/microsoftexcel-controlnet/scripts/batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "/content/microsoftexcel/modules/processing.py", line 680, in process_images_inner
        p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
      File "/content/microsoftexcel/modules/processing.py", line 1185, in init
        self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)
      File "/content/microsoftexcel/extensions/sd-multidiffusion-upscaler/scripts/tilediffusion.py", line 362, in <lambda>
        sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(
      File "/content/microsoftexcel/extensions/sd-multidiffusion-upscaler/scripts/tilediffusion.py", line 452, in create_sampler_hijack
        delegate.init_controlnet(self.controlnet_script, control_tensor_cpu)
      File "/content/microsoftexcel/extensions/sd-multidiffusion-upscaler/tile_utils/utils.py", line 243, in wrapper
        return fn(*args, **kwargs)
      File "/content/microsoftexcel/extensions/sd-multidiffusion-upscaler/tile_methods/abstractdiffusion.py", line 427, in init_controlnet
        self.prepare_controlnet_tensors()
      File "/content/microsoftexcel/extensions/sd-multidiffusion-upscaler/tile_utils/utils.py", line 243, in wrapper
        return fn(*args, **kwargs)
      File "/content/microsoftexcel/extensions/sd-multidiffusion-upscaler/tile_methods/abstractdiffusion.py", line 466, in prepare_controlnet_tensors
        control_tile = torch.cat(single_batch_tensors, dim=0)
    RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 512 but got size 256 for tensor number 1 in the list.

**Comment by re231** [comment]
any fix yet? i have try manually put vae opt from other thread
