### ISSUE TITLE
使用10月17日以后提交的版本在启动时出现模块依赖报错，导致界面不再显示tiled&vae模块

### ISSUE THREAD

**Issue by kamisaka108** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#315]
启动时控制台出现两段报错
第一段：
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.10.1, num models: 14
*** Error loading script: tilediffusion.py
    Traceback (most recent call last):
      File "E:\sd-webui\sd-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\sd-webui\sd-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\sd-webui\sd-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 71, in <module>
        from tile_methods.abstractdiffusion import AbstractDiffusion
      File "E:\sd-webui\sd-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py", line 12, in <module>
        from modules.shared_state import State
    ModuleNotFoundError: No module named 'modules.shared_state'

第二段：
*** Error loading script: tilevae.py
     Traceback (most recent call last):
      File "E:\sd-webui\sd-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\sd-webui\sd-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\sd-webui\sd-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilevae.py", line 71, in <module>
        from tile_utils.typing import Processing
      File "E:\sd-webui\sd-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\typing.py", line 14, in <module>
        from modules.sd_samplers_timesteps import VanillaStableDiffusionSampler
    ModuleNotFoundError: No module named 'modules.sd_samplers_timesteps'

**Comment by Kahsolt** [comment]
目前 API 升级到了 sd-webui v1.6
你暂时用的哪个版本

**Comment by kamisaka108** [comment]
目前使用的还是1.5.2 暂未更新到1.6

**Comment by Kahsolt** [comment]
最新的 commit #d91a9b7ac1ca8bac2f24fd70998998032c6da278 放宽了类型检查，可以试试

**Comment by kamisaka108** [comment]
commit [d91a9b7]版本启动时不会在出现报错了
但是在使用图生图时会出现页面提示 TypeError: typing.Any cannot be used with isinstance()
![OO`76CWE1HOKA55B%X@O`CU](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/129679783/0053595c-d931-49e9-b5e3-3a4521a7c175)

报错log中似乎和使用的lora-block-weight插件有关
以下是报错记录文档
[Diagnostics-1697790117.log](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/files/13051967/Diagnostics-1697790117.log)

**Comment by daniu85** [comment]
请问一下你解决了这个问题吗？我跟你使用的版本一模一样，也是升级后，界面不再显示tiled&vae模块，回滚之前的版本，就图生图报错，也是一模一样的错误。非常期待你的回复，感谢！

**Comment by kamisaka108** [comment]
作者目前是知道了这个问题似乎还未完成修复

**Comment by daniu85** [comment]
感谢，我最后更新到webui 1.6，目前能顺利出图了。

上坂蓮華 ***@***.***> 于2023年10月30日周一 18:28写道：

**Comment by 773774775** [comment]
遇到了同样的错误，SD版本1.5.2未升级到1.6，插件升级（git pull）之后界面就不再显示tiled&vae模块，而且还有脚本加载错误提示，有没有办法让插件回滚到未升级之前的版本啊？

**Comment by Kahsolt** [comment]
> 遇到了同样的错误，SD版本1.5.2未升级到1.6，插件升级（git pull）之后界面就不再显示tiled&vae模块，而且还有脚本加载错误提示，有没有办法让插件回滚到未升级之前的版本啊？

能看看现在的报错信息长啥样吗，我以为都修完了 :(

**Comment by 773774775** [comment]
> > 遇到了同样的错误，SD版本1.5.2未升级到1.6，插件升级（git pull）之后界面就不再显示tiled&vae模块，而且还有脚本加载错误提示，有没有办法让插件回滚到未升级之前的版本啊？
> 
> 能看看现在的报错信息长啥样吗，我以为都修完了 :(

*** Error loading script: tilediffusion.py
    Traceback (most recent call last):
      File "F:\tmp\stable-diffusion-webui-sr\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\tmp\stable-diffusion-webui-sr\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\tmp\stable-diffusion-webui-sr\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 71, in <module>
        from tile_methods.abstractdiffusion import AbstractDiffusion
      File "F:\tmp\stable-diffusion-webui-sr\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py", line 1, in <module>
        from tile_utils.utils import *
      File "F:\tmp\stable-diffusion-webui-sr\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 16, in <module>
        from tile_utils.typing import *
      File "F:\tmp\stable-diffusion-webui-sr\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\typing.py", line 14, in <module>
        from modules.shared_state import State
    ModuleNotFoundError: No module named 'modules.shared_state'

---
*** Error loading script: tilevae.py
    Traceback (most recent call last):
      File "F:\tmp\stable-diffusion-webui-sr\stable-diffusion-webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\tmp\stable-diffusion-webui-sr\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\tmp\stable-diffusion-webui-sr\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilevae.py", line 71, in <module>
        from tile_utils.typing import Processing
      File "F:\tmp\stable-diffusion-webui-sr\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\typing.py", line 14, in <module>
        from modules.shared_state import State
    ModuleNotFoundError: No module named 'modules.shared_state'

---

**Comment by kamisaka108** [comment]
感谢作者 最新的fbb2473版本1.5.2已经不出错了

**Comment by 773774775** [comment]
感谢作者大大的修复，在1.5.2下面可以正常使用了！👍
