### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'shape' when use Noise Inversion

### ISSUE THREAD

**Issue by zxwwxz001** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#316]
启用Noise Inversion的时候遇到错误AttributeError: 'dict' object has no attribute 'shape'

使用模型：animeArtDiffusionXL_alpha3.safetensors [53bb4fdc63]
插件为最新版（aa47321b）
具体错误信息如下
    Traceback (most recent call last):
      File "/notebooks/sdwebui/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/notebooks/sdwebui/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/notebooks/sdwebui/stable-diffusion-webui/modules/img2img.py", line 208, in img2img
        processed = process_images(p)
      File "/notebooks/sdwebui/stable-diffusion-webui/modules/processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "/notebooks/sdwebui/stable-diffusion-webui/modules/processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/notebooks/sdwebui/stable-diffusion-webui/modules/processing.py", line 1528, in sample
        samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
      File "/notebooks/sdwebui/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_utils/utils.py", line 246, in wrapper
        return fn(*args, **kwargs)
      File "/notebooks/sdwebui/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_utils/utils.py", line 246, in wrapper
        return fn(*args, **kwargs)
      File "/notebooks/sdwebui/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/abstractdiffusion.py", line 652, in sample_img2img
        latent = self.find_noise_for_image_sigma_adjustment(sampler.model_wrap, self.noise_inverse_steps, prompts)
      File "/notebooks/sdwebui/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_utils/utils.py", line 246, in wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/notebooks/sdwebui/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/abstractdiffusion.py", line 729, in find_noise_for_image_sigma_adjustment
        eps = self.get_noise(x_in * c_in, t, cond_in, steps - i)
      File "/notebooks/sdwebui/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/multidiffusion.py", line 243, in get_noise
        return self.sample_one_step(x_in, org_func, repeat_func, custom_func)
      File "/notebooks/sdwebui/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/multidiffusion.py", line 165, in sample_one_step
        x_tile_out = repeat_func(x_tile, bboxes)
      File "/notebooks/sdwebui/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/multidiffusion.py", line 229, in repeat_func
        cond_out = self.repeat_cond_dict(cond_in_original, bboxes)
      File "/notebooks/sdwebui/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/multidiffusion.py", line 118, in repeat_cond_dict
        tcond = self.repeat_tensor(tcond, n_rep)
      File "/notebooks/sdwebui/stable-diffusion-webui/extensions/multidiffusion-upscaler-for-automatic1111/tile_methods/multidiffusion.py", line 103, in repeat_tensor
        B = x.shape[0]
    AttributeError: 'dict' object has no attribute 'shape'

**Comment by Kahsolt** [comment]
对SDXL的支持还需要更多兼容性测试，感谢错误报告~
可能这个ckpt用到了某些暂未解析的 cond_dict 键，我先去下载来看看
