### ISSUE TITLE
 AttributeError: 'KDiffusionSampler' object has no attribute 'step'

### ISSUE THREAD

**Issue by galauluulul** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#317]
*** Error completing request
*** Arguments: ('task(qc6wbjbveg9po0e)', '(masterpiece), (artwork), (amazing masterpiece), (best illustration), (best coloring), (extremely detailed CG 8k unity wallpaper),', '(low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2), bad composition, inaccurate eyes, extra digit, fewer digits, (extra arms:1.2), (low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2), bad composition, inaccurate eyes, extra digit, fewer digits, (extra arms:1.2), No colored hair, no texts, names, artist signature, logo, watermark, company name, poor quality, bold texts, characters, numbers, barcode.', [], 20, 'Euler a', 1, 1, 7, 512, 512, True, 0.7, 1.5, 'Latent', 7, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000002C1DE4C3B20>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, True, False, False, True, 0, 0, 1, 1, 'in bathroom', '', 'Background', 0.2, -1.0, True, 0.25416666666666665, 0.07916666666666672, 0.5291666666666666, 0.8541666666666667, 'A nude woman , big breasts, short hair, pubic hair, full body, nipples, braided chignon, light brown color hair, standing, realistic photo, pussy, bathroom, damp, fog, wet,', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, True, 960, 64, True, True, True, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "C:\Users\ynot3\Downloads\sd.webui\webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\ynot3\Downloads\sd.webui\webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\modules\processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\modules\processing.py", line 1140, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "C:\Users\ynot3\Downloads\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\Users\ynot3\Downloads\sd.webui\webui\modules\sd_samplers_common.py", line 261, in launch_sampling
        return func()
      File "C:\Users\ynot3\Downloads\sd.webui\webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
      File "C:\Users\ynot3\Downloads\sd.webui\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "C:\Users\ynot3\Downloads\sd.webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\modules\sd_samplers_cfg_denoiser.py", line 188, in forward
        x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
      File "C:\Users\ynot3\Downloads\sd.webui\system\python\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\ynot3\Downloads\sd.webui\system\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 246, in wrapper
        return fn(*args, **kwargs)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py", line 70, in kdiff_forward
        return self.sample_one_step(x_in, org_func, repeat_func, custom_func)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py", line 187, in sample_one_step
        x_tile_out = custom_func(x_tile, bbox_id, bbox)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py", line 68, in custom_func
        return self.kdiff_custom_forward(x, sigma_in, cond, bbox_id, bbox, self.sampler_forward)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 246, in wrapper
        return fn(*args, **kwargs)
      File "C:\Users\ynot3\Downloads\sd.webui\webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py", line 264, in kdiff_custom_forward
        if self.kdiff_step != self.sampler.step:
    AttributeError: 'KDiffusionSampler' object has no attribute 'step'

求助!

**Comment by Omg-ciTy** [comment]
我也是出上面的错误 用的是SD1.5的模型 退回4a6e331 20231016210502的版本就不出错了
I also made the above mistake using the SD1.5 model, and returning the 4a6e331 version 20231016210502 without error

**Comment by 4lt3r3go** [comment]
same error here, only when activating REGIO PROMPT CONTROL
