### ISSUE TITLE
Prompts with 'AND' causes runtime exception

### ISSUE THREAD

**Issue by f0lie** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#32]
```python
Traceback (most recent call last):
  File "C:\Users\asdf\ai\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\asdf\ai\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\asdf\ai\stable-diffusion-webui\modules\img2img.py", line 171, in img2img
    processed = process_images(p)
  File "C:\Users\asdf\ai\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\Users\asdf\ai\stable-diffusion-webui\modules\processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\Users\asdf\ai\stable-diffusion-webui\modules\processing.py", line 1054, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "C:\Users\asdf\ai\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 324, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Users\asdf\ai\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "C:\Users\asdf\ai\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 324, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Users\asdf\miniconda3\envs\auto\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\asdf\ai\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\asdf\miniconda3\envs\auto\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\asdf\ai\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 140, in forward
    x_out[-uncond.shape[0]:] = self.inner_model(x_in[-uncond.shape[0]:], sigma_in[-uncond.shape[0]:], cond={"c_crossattn": [uncond], "c_concat": [image_cond_in[-uncond.shape[0]:]]})
RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [1, 4, 384, 256].  Tensor sizes: [2, 4, 384, 256]
```

OS: Windows 11
GPU: Nvidia 4090

It looks independent of my settings. I got it to work on other images so it seems like some images break the code.

**Comment by f0lie** [comment]
I figured out why. I was using the 'AND' clause in my prompt image. So `hello AND world` will break the code.

This explanation makes sense, `Target sizes: [1, 4, 384, 256].  Tensor sizes: [2, 4, 384, 256]` these two tensors are only different by 1 and 2 dimensions.

**Comment by pkuliyi2015** [comment]
Really thanks for pointing this out. I will further investigate.

**Comment by pkuliyi2015** [comment]
Please try again in this version. It should work now.
