### ISSUE TITLE
DDIM sampler could not be used in Tiled DIffusion (img2img)

### ISSUE THREAD

**Issue by cheezecrisp** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#327]
It works well when using other samplers, but error occurs when using DDIM. Error message as below:

`    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\AI\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\AI\stable-diffusion-webui\modules\img2img.py", line 208, in img2img
        processed = process_images(p)
      File "D:\AI\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "D:\AI\stable-diffusion-webui\modules\processing.py", line 803, in process_images_inner
        p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
      File "D:\AI\stable-diffusion-webui\modules\processing.py", line 1392, in init
        self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)
      File "D:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 362, in <lambda>
        sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(
      File "D:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 459, in create_sampler_hijack
        delegate.hook()
      File "D:\AI\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py", line 33, in hook
        self.sampler_forward = self.sampler.orig_p_sample_ddim
    AttributeError: 'CompVisSampler' object has no attribute 'orig_p_sample_ddim'`

I'm not sure if this is a bug or just my problem.

**Comment by Kahsolt** [comment]
This is a known issue, sd-webui changed a lot on handling DDIM seires samplers since v1.5.2, our code is obsolete and need update
However this extension is at the edging of being abandoned now...

**Comment by cheezecrisp** [comment]
> This is a known issue, sd-webui changed a lot on handling DDIM seires samplers since v1.5.2, our code is obsolete and need update However this extension is at the edging of being abandoned now...

Sad 😢

**Comment by pkuliyi2015** [comment]
> This is a known issue, sd-webui changed a lot on handling DDIM seires samplers since v1.5.2, our code is obsolete and need update However this extension is at the edging of being abandoned now...

I'm still alive bro, but I didn't use DDIM. So far the extension works well on SDXL on my side.

**Comment by highnrgappalachian** [comment]
All the SDXL fiasco did was splinter the community. Come back to us, your 1.5 children.

**Comment by cheezecrisp** [comment]
> > This is a known issue, sd-webui changed a lot on handling DDIM seires samplers since v1.5.2, our code is obsolete and need update However this extension is at the edging of being abandoned now...
> 
> I'm still alive bro, but I didn't use DDIM. So far the extension works well on SDXL on my side.

DDIM works best for me when upscaling realistic img, it gives natural human skin texture and analog grain, you should have a try.
