### ISSUE TITLE
Cannot use different sampler during hires fix running tiled diffusion

### ISSUE THREAD

**Issue by sashasubbbb** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#332]
When trying to use a different sampler during hires fix this error occurs:
```
    Traceback (most recent call last):
      File "B:\AIimages\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "B:\AIimages\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "B:\AIimages\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "B:\AIimages\stable-diffusion-webui\modules\processing.py", line 734, in process_images
        res = process_images_inner(p)
      File "B:\AIimages\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "B:\AIimages\stable-diffusion-webui\modules\processing.py", line 869, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "B:\AIimages\stable-diffusion-webui\modules\processing.py", line 1161, in sample
        return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
      File "B:\AIimages\stable-diffusion-webui\modules\processing.py", line 1186, in sample_hr_pass
        self.sampler = sd_samplers.create_sampler(img2img_sampler_name, self.sd_model)
      File "B:\AIimages\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 357, in <lambda>
        sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(
      File "B:\AIimages\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 429, in create_sampler_hijack
        sampler = Script.create_sampler_original_md(name, model)
    AttributeError: type object 'Script' has no attribute 'create_sampler_original_md'
```

**Comment by n0kovo** [comment]
+1
