### ISSUE TITLE
"TypeError: must be real number, not NoneType" when trying to use Region Prompt Control. Using SDXL, in case it matters.

### ISSUE THREAD

**Issue by Manchovies** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#346]
`*** Error completing request
*** Arguments: ('task(zwfjlvs2uko8hna)', <gradio.routes.Request object at 0x0000024666E31990>, 'hyperdetailed photography,  minimalist art sculpture, metallic sculpture, product photograph, desktop wallpaper,', '', [], 20, 'DPM++ 2M Karras', 1, 4, 7, 1344, 768, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, True, 'C-Drive-SDXLRefiner1.0-pruned-no-ema.safetensors [9bfca2abbc]', 0.8, -1, False, -1, 0, 0, 0, True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, True, False, False, True, 0, 0, 0.9999999999999997, 0.5991, 'vantablack metallic chrysanthemum flower, with slight accents of color on the bud in the center, on a dark blue and red leather background', '', 'Foreground', 0.2, -1.0, True, 0, 0.575, 1, 0.425, 'vantablack metallic flower stem, slight accents of color near the bottom of the flower stem, on a dark blue and red leather background', '', 'Foreground', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 1536, 96, True, True, True, False, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\processing.py", line 782, in process_images
        res = process_images_inner(p)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\processing.py", line 944, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\processing.py", line 1256, in sample
        self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 357, in <lambda>
        sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 445, in create_sampler_hijack
        delegate.init_custom_bbox(bbox_settings, draw_background, causal_layers)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 249, in wrapper
        return fn(*args, **kwargs)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\multidiffusion.py", line 42, in init_custom_bbox
        super().init_custom_bbox(*args)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 249, in wrapper
        return fn(*args, **kwargs)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py", line 226, in init_custom_bbox
        bbox.cond, bbox.extra_network_data = Condition.get_custom_cond(prompts, bbox.prompt, p.steps, p.styles)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 123, in get_custom_cond
        cond = Condition.get_cond(prompts, steps)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 129, in get_cond
        cond = prompt_parser.get_multicond_learned_conditioning(shared.sd_model, prompts, steps)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\prompt_parser.py", line 261, in get_multicond_learned_conditioning
        learned_conditioning = get_learned_conditioning(model, prompt_flat_list, steps, hires_steps, use_old_scheduling)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\prompt_parser.py", line 188, in get_learned_conditioning
        conds = model.get_learned_conditioning(texts)
      File "D:\Users\Spencer\Downloads\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI\modules\sd_models_xl.py", line 25, in get_learned_conditioning
        "original_size_as_tuple": torch.tensor([height, width], **devices_args).repeat(len(batch), 1),
    TypeError: must be real number, not NoneType
`

Happens with or without refiner. I'm on v1.7.0-437-gce168ab5 of Automatic1111. Fresh install of everything. Tried with FP8 and without, because that is something else I've been playing with. Tried with and without Tiled VAE. No luck so far. Any ideas? Happy to try anything you need or provide more info if needed. It's very reproducible on my system. Thanks for the extension btw :)

**Comment by YondSun** [comment]
SDXL +1

**Comment by solonrice** [comment]
This happens on 1.8.0 (dev branch). After the error, I can switch to a 1.5 model and it works. Switch back to SDXL and the error throws again.

**Comment by aresmar2077** [comment]
1.8 version of A1111, regional promps not working with SDXL I can confirm too.

**Comment by giux77** [comment]
SDXL +1

**Comment by carlosgalveias** [comment]
SDXL +1

**Comment by SuccySuccuba** [comment]
SDXL +1

**Comment by LoRAMilkshake** [comment]
SDXL throws this error when trying to use Multidiffusion regional prompter

**Comment by LindezaBlue** [comment]
same issue +1

**Comment by baatrk** [comment]
> This happens on 1.8.0 (dev branch). After the error, I can switch to a 1.5 model and it works. Switch back to SDXL and the error throws again.

did you use tiled region prompt control with sdxl model before 1.8.0?
