### ISSUE TITLE
[Feature Request] Support for Stable Diffusion Forge

### ISSUE THREAD

**Issue by Vigilence** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#350]
I would love to see official support for [stable diffusion forge](https://github.com/lllyasviel/stable-diffusion-webui-forge).  It is made by the creator of the controlnet extension. It has the same UI as automatic1111, but the backend has been revised with additional code so that its more memory efficient.

Your tiled vae part of this extension has been successfully integrated into the project.  And some of the tiled diffusion part has also been integrated.  However, I don't believe it functions the same as the author of forge states that he is confused as how it would work with the upscaler, so that part has been stripped out.

If perhaps you can help make the changes needed so that your extension fully works in forge that would be great.  Some of your extension is already done, so hopefully that means less work for you.

**Comment by LindezaBlue** [comment]
I agree, I too am wanting this as there is no support for it at the moment.

**Comment by Manchovies** [comment]
I don't know if this is worth anything, but also chiming in here with this request. Forge is great and I miss using this extension so much, but the benefits of using forge without outweigh the usage of vanilla Automatic at the moment. Thanks for your work! :)

**Comment by ItsAuver** [comment]
+1 for this request

**Comment by Pervertica** [comment]
+1

**Comment by williw89** [comment]
My comrade! This is an urgent task, a top priority!

**Comment by LindezaBlue** [comment]
Forge is way faster than A1111, I really want to use this extension, but I can't go back to A1111.

**Comment by abubasal** [comment]
+1. wow I thought for sure this would be in forged but i was shocked to see the integrated version is not the same thing at all! please provide support for forge

**Comment by Kahsolt** [comment]
Receiving many voices for migrating to sd-webui-forge :)
However, our friend @pkuliyi2015 is so busy with his graduation and essays, me also hard working on ML contests...

What about listening to @lllyasviel's advice? 🤔
What's forge's roadmap for this multi-diff? Will you re-write these all (to satisfy that new framework)?

**Comment by LiJT** [comment]
> Receiving many voices for migrating to sd-webui-forge :) However, our friend @pkuliyi2015 is so busy with his graduation and essays, me also hard working on ML contests...
> 
> What about listening to @lllyasviel's advice? 🤔 What's forge's roadmap for this multi-diff? Will you re-write these all (to satisfy that new framework)?

大佬哭求更新，Forge目前的Multi diffusion少了一个重要功能没有Noise Inversion, 实在是难受

**Comment by LindezaBlue** [comment]
> Receiving many voices for migrating to sd-webui-forge :) However, our friend @pkuliyi2015 is so busy with his graduation and essays, me also hard working on ML contests...
> 
> What about listening to @lllyasviel's advice? 🤔 What's forge's roadmap for this multi-diff? Will you re-write these all (to satisfy that new framework)?

I think it would be well worth it to get it running on the new forge webui. As it is the extension for Multi-Diffusion is really good, and very fast.. and if it was paired with the speed of forge, the render time for images would be really good. 

I understand people get busy, I'm not expecting it to be updated within the next month or so. Programming is difficult work and takes time, and life happens, it would be nice to see a status update that it is in the works, or something similar.

**Comment by ryanull24** [comment]
+1 would like to see this working in Forge.

**Comment by philmcrakin** [comment]
+1

**Comment by wangfeng35** [comment]
+1

**Comment by LindezaBlue** [comment]
+2

**Comment by Myoko** [comment]
This is a very useful extension, hopefully it will work on forge.

**Comment by louiskaneko34m** [comment]
+999999

**Comment by Kahsolt** [comment]
After I carefully checked the forge's implementation, I found that it is actually syncing with the [ComfyUI version](https://github.com/shiimizu/ComfyUI-TiledDiffusion), hence only basic functionality is available.
I think we're not responsible for this :(
Though I must say the forge is really really fucking fast...

**Comment by LindezaBlue** [comment]
> After I carefully checked the forge's implementation, I found that it is actually syncing with the [ComfyUI version](https://github.com/shiimizu/ComfyUI-TiledDiffusion), hence only basic functionality is available. I think we're not responsible for this :( Though I must say the forge is really really fucking fast...

Interesting, the devs over at forge say it's a fork of A1111, but if it is syncing with ComfyUI... That would explain a lot especially since Multi-Diffusion works with the latest version of A1111.

I wonder if there is a workaround to get functionality on Forge... SD.Next doesn't even come close to forges speed, and it's a definite improvement over A1111.

**Comment by Kahsolt** [comment]
Forge's integration of this extension is not well-arranged. 
Based on my own understanding, it's copied from the ComfyUI version, then been modified to suit into the sd-webui framework, and leaving much redundancies and danglings in code text -- it is hard to manage and remake it right & beautiful.

**Comment by LindezaBlue** [comment]
> Forge's integration of this extension is not well-arranged. Based on my own understanding, it's copied from the ComfyUI version, then been modified to suit into the sd-webui framework, and leaving much redundancies and danglings in code text -- it is hard to manage and remake it right & beautiful.

Does that mean there is potential for the webui (forge) to improve in performance if properly optimized and earned up? That would be amazing if that was the case.

**Comment by Kahsolt** [comment]
> > Forge's integration of this extension is not well-arranged. Based on my own understanding, it's copied from the ComfyUI version, then been modified to suit into the sd-webui framework, and leaving much redundancies and danglings in code text -- it is hard to manage and remake it right & beautiful.
> 
> Does that mean there is potential for the webui (forge) to improve in performance if properly optimized and earned up? That would be amazing if that was the case.

Yes, but please consider what this mean to us...

ComfyUI implements a subset of the A1111's, and then forge borrows from (a maybe subset of) ComfyUI.
Then when there's a new feature or bugfix of the original A1111, we'll have to fix it at 3 places...
kill me, thx

**Comment by LindezaBlue** [comment]
> > > Forge's integration of this extension is not well-arranged. Based on my own understanding, it's copied from the ComfyUI version, then been modified to suit into the sd-webui framework, and leaving much redundancies and danglings in code text -- it is hard to manage and remake it right & beautiful.
> > 
> > 
> > Does that mean there is potential for the webui (forge) to improve in performance if properly optimized and earned up? That would be amazing if that was the case.
> 
> Yes, but please consider what this mean to us...
> 
> ComfyUI implements a subset of the A1111's, and then forge borrows from (a maybe subset of) ComfyUI. Then when there's a new feature or bugfix of the original A1111, we'll have to fix it at 3 places... kill me, thx

My god that sounds like a pain beyond imagination. I sincerely hope it doesn't end up being that much work. I mean if it does and it turns out it would be hard to implement it, no worries. I'm no programmer, but I do understand the workload. And if it's not worth it, then it's not worth it. 

Either way keep up the outstanding work! 😁👍🏼
You have our support one way or the other! 🫂

**Comment by LindezaBlue** [comment]
Tested with latest model, tried tweaking settings and still can't force it to work with forge. 
![image](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/assets/141217866/ebaaab8b-ec56-4ed0-a7a9-149cdef6f220)

**Comment by Vigilence** [comment]
> Tested with latest model, tried tweaking settings and still can't force it to work with forge. ![image](https://private-user-images.githubusercontent.com/141217866/322309632-ebaaab8b-ec56-4ed0-a7a9-149cdef6f220.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDQ2MTMsIm5iZiI6MTcxMzI0NDMxMywicGF0aCI6Ii8xNDEyMTc4NjYvMzIyMzA5NjMyLWViYWFhYjhiLWVjNTYtNGVkMC1hN2E5LTE0OWNkZWY2ZjIyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNTExNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2VhODRhYTg0MGJlODI5MDQxNzNjZWEwZmExYTExNjNiODcwN2Y3YmU5YzVjNGMyNGE5OTYwNmQ5Y2ZhYWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LEIN63l7eolQiYKSBtFr1Fvqh95LaPScSPoWSpntwpk)

Forge author hard coded this extension to be disabled.  You would have to request him to remove that disable code.

**Comment by LindezaBlue** [comment]
> > Tested with latest model, tried tweaking settings and still can't force it to work with forge. ![image](https://private-user-images.githubusercontent.com/141217866/322309632-ebaaab8b-ec56-4ed0-a7a9-149cdef6f220.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNDQ2MTMsIm5iZiI6MTcxMzI0NDMxMywicGF0aCI6Ii8xNDEyMTc4NjYvMzIyMzA5NjMyLWViYWFhYjhiLWVjNTYtNGVkMC1hN2E5LTE0OWNkZWY2ZjIyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNTExNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2VhODRhYTg0MGJlODI5MDQxNzNjZWEwZmExYTExNjNiODcwN2Y3YmU5YzVjNGMyNGE5OTYwNmQ5Y2ZhYWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LEIN63l7eolQiYKSBtFr1Fvqh95LaPScSPoWSpntwpk)
> 
> Forge author hard coded this extension to be disabled. You would have to request him to remove that disable code.

I have opened up a new ticket with the Forge Developers to see if we can get them to re-enable the extension so that it can either be used, or worked on to get support in Forge. 

I would highly encourage everyone here that wants this extension to be supported in Forge to head over to this post and comment there so the Devs of Forge get the ball moving.

https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/672

**Comment by gigend** [comment]
any update for tiled diffusion with upscaler?

**Comment by Reptile-MTK** [comment]
It is a shame that it is still not supported. I really would love to try the regional prompt control. It looks amazing.

**Comment by Dravoss** [comment]
i have enabled it in forge neo with https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/363#issuecomment-2923283521 but it still does not work, i get this error every time when launching forge:

*** Error loading script: tilediffusion.py
    Traceback (most recent call last):
      File "C:\WebUI\sd-webui-forge-neo\modules\scripts.py", line 530, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\WebUI\sd-webui-forge-neo\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
      File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "C:\WebUI\sd-webui-forge-neo\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 71, in <module>
        from tile_methods.abstractdiffusion import AbstractDiffusion
      File "C:\WebUI\sd-webui-forge-neo\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py", line 1, in <module>
        from tile_utils.utils import *
      File "C:\WebUI\sd-webui-forge-neo\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 16, in <module>
        from tile_utils.typing import *
      File "C:\WebUI\sd-webui-forge-neo\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\typing.py", line 8, in <module>
        from k_diffusion.external import CompVisDenoiser, CompVisVDenoiser
    ImportError: cannot import name 'CompVisDenoiser' from 'k_diffusion.external' (C:\WebUI\sd-webui-forge-neo\modules_forge\packages\k_diffusion\external.py)

---
*** Error loading script: tileglobal.py
    Traceback (most recent call last):
      File "C:\WebUI\sd-webui-forge-neo\modules\scripts.py", line 530, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\WebUI\sd-webui-forge-neo\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
      File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "C:\WebUI\sd-webui-forge-neo\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tileglobal.py", line 13, in <module>
        from tile_methods.abstractdiffusion import AbstractDiffusion
      File "C:\WebUI\sd-webui-forge-neo\extensions\multidiffusion-upscaler-for-automatic1111\tile_methods\abstractdiffusion.py", line 1, in <module>
        from tile_utils.utils import *
      File "C:\WebUI\sd-webui-forge-neo\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\utils.py", line 16, in <module>
        from tile_utils.typing import *
      File "C:\WebUI\sd-webui-forge-neo\extensions\multidiffusion-upscaler-for-automatic1111\tile_utils\typing.py", line 8, in <module>
        from k_diffusion.external import CompVisDenoiser, CompVisVDenoiser
    ImportError: cannot import name 'CompVisDenoiser' from 'k_diffusion.external' (C:\WebUI\sd-webui-forge-neo\modules_forge\packages\k_diffusion\external.py)

---
*** Error loading script: tilevae.py
    Traceback (most recent call last):
      File "C:\WebUI\sd-webui-forge-neo\modules\scripts.py", line 530, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\WebUI\sd-webui-forge-neo\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
      File "<frozen importlib._bootstrap_external>", line 1023, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "C:\WebUI\sd-webui-forge-neo\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilevae.py", line 68, in <module>
        from ldm.modules.diffusionmodules.model import AttnBlock, MemoryEfficientAttnBlock
    ModuleNotFoundError: No module named 'ldm'
