### ISSUE TITLE
Help me,pls

### ISSUE THREAD

**Issue by xlibfly** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#374]
[Tiled VAE]: the input size is tiny and unnecessary to tile.
[Tiled VAE]: input_size: torch.Size([1, 4, 120, 240]), tile_size: 192, padding: 11
[Tiled VAE]: split to 1x2 = 2 tiles. Optimal tile size 128x128, original tile size 192x192
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 192 x 96 image
[Tiled VAE]: Done in 1.433s, max VRAM alloc 5263.884 MB
*** Error running postprocess_batch_list: D:\sd-webui-aki-v4.5\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tileglobal.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.5\modules\scripts.py", line 832, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\sd-webui-aki-v4.5\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tileglobal.py", line 227, in postprocess_batch_list
        pp.images[idx] = image[:,:image.shape[1]//(p.scale_factor)*(idx_b+1),:image.shape[2]//(p.scale_factor)*(idx_b+1)]
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'scale_factor'

---
[Tiled VAE]: the input size is tiny and unnecessary to tile.
[Tiled VAE]: the input size is tiny and unnecessary to tile.
*** Error running postprocess_batch_list: D:\sd-webui-aki-v4.5\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tileglobal.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.5\modules\scripts.py", line 832, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\sd-webui-aki-v4.5\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tileglobal.py", line 227, in postprocess_batch_list
        pp.images[idx] = image[:,:image.shape[1]//(p.scale_factor)*(idx_b+1),:image.shape[2]//(p.scale_factor)*(idx_b+1)]
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'scale_factor'

---
[Tiled VAE]: the input size is tiny and unnecessary to tile.
[Tiled VAE]: the input size is tiny and unnecessary to tile.
*** Error running postprocess_batch_list: D:\sd-webui-aki-v4.5\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tileglobal.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.5\modules\scripts.py", line 832, in postprocess_batch_list
        script.postprocess_batch_list(p, pp, *script_args, **kwargs)
      File "D:\sd-webui-aki-v4.5\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tileglobal.py", line 227, in postprocess_batch_list
        pp.images[idx] = image[:,:image.shape[1]//(p.scale_factor)*(idx_b+1),:image.shape[2]//(p.scale_factor)*(idx_b+1)]
    AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'scale_factor'

---

**Comment by heftig** [comment]
duplicate of #372

**Comment by Jaylen-Lee** [comment]
just update to latest version， and this bug has been fixed
