### ISSUE TITLE
Batch count size > 1 causes a stretched images from the second one

### ISSUE THREAD

**Issue by binary-zero-one** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#46]
If you set the batch count size greater than 1, all subsequent images from the second onwards will be generated with an incorrect ratio. This is particularly noticeable when using ControlNet. Looks like an extension is not hooked for the second generation
<details>
  <summary>UI</summary>

  ![ui](https://user-images.githubusercontent.com/75141398/226421984-11c9ad2c-c3f5-4e75-a02f-a61bff54674e.png)
</details>

<details>
  <summary>Console log</summary>

  ```[Tiled Diffusion] ControlNet found, MultiDiffusion-ControlNet support is enabled.
  Loading model from cache: control_canny [e3fe7712]
  Loading preprocessor: canny
  MultiDiffusion hooked into DPM++ 2M Karras sampler. Tile size: 96x96, Tile batches: 2, Batch size: 1
    0% 0/15 [00:00<?, ?it/s]
  MultiDiffusion Sampling:   0% 0/30 [00:00<?, ?it/s]
  MultiDiffusion Sampling:   3% 1/30 [00:00<00:11,  2.49it/s]
    7% 1/15 [00:01<00:16,  1.19s/it]
   13% 2/15 [00:02<00:14,  1.15s/it]
  MultiDiffusion Sampling:   7% 2/30 [00:03<00:50,  1.79s/it]
   20% 3/15 [00:03<00:13,  1.13s/it]
  MultiDiffusion Sampling:  10% 3/30 [00:04<00:40,  1.49s/it]
   27% 4/15 [00:04<00:12,  1.13s/it]
  MultiDiffusion Sampling:  13% 4/30 [00:05<00:34,  1.34s/it]
   33% 5/15 [00:05<00:11,  1.13s/it]
  MultiDiffusion Sampling:  17% 5/30 [00:06<00:31,  1.27s/it]
   40% 6/15 [00:06<00:10,  1.13s/it]
  MultiDiffusion Sampling:  20% 6/30 [00:07<00:29,  1.21s/it]
   47% 7/15 [00:07<00:08,  1.12s/it]
  MultiDiffusion Sampling:  23% 7/30 [00:08<00:27,  1.19s/it]
   53% 8/15 [00:09<00:07,  1.12s/it]
  MultiDiffusion Sampling:  27% 8/30 [00:09<00:25,  1.16s/it]
   60% 9/15 [00:10<00:06,  1.12s/it]
  MultiDiffusion Sampling:  30% 9/30 [00:11<00:24,  1.15s/it]
   67% 10/15 [00:11<00:05,  1.12s/it]
  MultiDiffusion Sampling:  33% 10/30 [00:12<00:22,  1.14s/it]
   73% 11/15 [00:12<00:04,  1.12s/it]
  MultiDiffusion Sampling:  37% 11/30 [00:13<00:21,  1.14s/it]
   80% 12/15 [00:13<00:03,  1.12s/it]
  MultiDiffusion Sampling:  40% 12/30 [00:14<00:20,  1.13s/it]
   87% 13/15 [00:14<00:02,  1.12s/it]
  MultiDiffusion Sampling:  43% 13/30 [00:15<00:19,  1.13s/it]
   93% 14/15 [00:15<00:01,  1.12s/it]
  MultiDiffusion Sampling:  47% 14/30 [00:16<00:18,  1.13s/it]
  100% 15/15 [00:16<00:00,  1.13s/it]
    0% 0/15 [00:00<?, ?it/s]
    7% 1/15 [00:00<00:11,  1.24it/s]
   13% 2/15 [00:01<00:10,  1.25it/s]
   20% 3/15 [00:02<00:09,  1.24it/s]
   27% 4/15 [00:03<00:08,  1.24it/s]
   33% 5/15 [00:04<00:08,  1.24it/s]
   40% 6/15 [00:04<00:07,  1.24it/s]
   47% 7/15 [00:05<00:06,  1.24it/s]
   53% 8/15 [00:06<00:05,  1.23it/s]
   60% 9/15 [00:07<00:04,  1.24it/s]
   67% 10/15 [00:08<00:04,  1.23it/s]
   73% 11/15 [00:08<00:03,  1.24it/s]
   80% 12/15 [00:09<00:02,  1.23it/s]
   87% 13/15 [00:10<00:01,  1.24it/s]
   93% 14/15 [00:11<00:00,  1.23it/s]
  100% 15/15 [00:12<00:00,  1.24it/s]
  MultiDiffusion Sampling:  47% 14/30 [00:40<00:46,  2.88s/it]
  Total progress: 100% 30/30 [00:39<00:00,  1.31s/it]
  ```
</details>

<details>
  <summary>Images</summary>

  ![car-original](https://user-images.githubusercontent.com/75141398/226423837-f6b93b92-014e-43af-9789-d25ece658800.png)

  ![canny](https://user-images.githubusercontent.com/75141398/226423850-8f0c9c87-9bd0-47d6-98a1-112d8e890486.png)
  
  ![grid](https://user-images.githubusercontent.com/75141398/226423863-923eb0fb-4cad-4a5a-9619-ee3643de8f9a.png)
</details>

There is also an exception if you set "Latent tile batch size" greater than 1 with batch count size >1.
<details>
  <summary>Exception</summary>

  ```[Tiled Diffusion] ControlNet found, MultiDiffusion-ControlNet support is enabled.
  Loading model from cache: control_canny [e3fe7712]
  Loading preprocessor: canny
  MultiDiffusion hooked into DPM++ 2M Karras sampler. Tile size: 96x96, Tile batches: 1, Batch size: 2
    0% 0/15 [00:00<?, ?it/s]
  MultiDiffusion Sampling:   0% 0/15 [00:00<?, ?it/s]
    7% 1/15 [00:01<00:15,  1.14s/it]
   13% 2/15 [00:02<00:14,  1.11s/it]
   20% 3/15 [00:03<00:13,  1.09s/it]
   27% 4/15 [00:04<00:11,  1.09s/it]
   33% 5/15 [00:05<00:10,  1.09s/it]
   40% 6/15 [00:06<00:09,  1.08s/it]
   47% 7/15 [00:07<00:08,  1.08s/it]
   53% 8/15 [00:08<00:07,  1.08s/it]
   60% 9/15 [00:09<00:06,  1.08s/it]
   67% 10/15 [00:10<00:05,  1.08s/it]
   73% 11/15 [00:11<00:04,  1.09s/it]
   80% 12/15 [00:13<00:03,  1.09s/it]
   87% 13/15 [00:14<00:02,  1.09s/it]
   93% 14/15 [00:15<00:01,  1.08s/it]
  100% 15/15 [00:16<00:00,  1.09s/it]
    0% 0/15 [00:00<?, ?it/s]
  Error completing request
  Arguments: ('task(xxxxxxxxxxxxxxx)', 'a car, road, mountains', '', [], 15, 8, False, False, 2, 1, 8, -1.0, -1.0, 0, 640, 640, False, 960, 768, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 2, 'None', 2, False, False, 1, False, 1, 7, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 7, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 7, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 7, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 7, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 7, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 7, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 7, 0.4, 0.4, 0.2, 0.2, '', '', False, False, True, True, True, 2048, 128, True, False, 1, False, False, False, 1.1, 1.5, 70, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 6, 95, 'Cosine Up', 4, 'Cosine Up', 4, 0, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.external_code.ControlNetUnit object at 0x>, <scripts.external_code.ControlNetUnit object at 0x>, <scripts.external_code.ControlNetUnit object at 0x>, <scripts.external_code.ControlNetUnit object at 0x>, <scripts.external_code.ControlNetUnit object at 0x>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, True, True, False, 0, None, False, None, False, None, False, None, False, None, False, 50) {}
  Traceback (most recent call last):
    File "/path-to-auto1111-webui/modules/call_queue.py", line 56, in f
      res = list(func(*args, **kwargs))
    File "/path-to-auto1111-webui/modules/call_queue.py", line 37, in f
      res = func(*args, **kwargs)
    File "/path-to-auto1111-webui/modules/txt2img.py", line 56, in txt2img
      processed = process_images(p)
    File "/path-to-auto1111-webui/modules/processing.py", line 486, in process_images
      res = process_images_inner(p)
    File "/path-to-auto1111-webui/modules/processing.py", line 636, in process_images_inner
      samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
    File "/path-to-auto1111-webui/modules/processing.py", line 836, in sample
      samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
    File "/path-to-auto1111-webui/modules/sd_samplers_kdiffusion.py", line 351, in sample
      samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
    File "/path-to-auto1111-webui/modules/sd_samplers_kdiffusion.py", line 227, in launch_sampling
      return func()
    File "/path-to-auto1111-webui/modules/sd_samplers_kdiffusion.py", line 351, in <lambda>
      samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
    File "/usr/local/lib/python3.9/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
      return func(*args, **kwargs)
    File "/path-to-auto1111-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
      denoised = model(x, sigmas[i] * s_in, **extra_args)
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
      return forward_call(*input, **kwargs)
    File "/path-to-auto1111-webui/modules/sd_samplers_kdiffusion.py", line 119, in forward
      x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
      return forward_call(*input, **kwargs)
    File "/path-to-auto1111-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
      eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
    File "/path-to-auto1111-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
      return self.inner_model.apply_model(*args, **kwargs)
    File "/path-to-auto1111-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
      setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
    File "/path-to-auto1111-webui/modules/sd_hijack_utils.py", line 28, in __call__
      return self.__orig_func(*args, **kwargs)
    File "/path-to-auto1111-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
      x_recon = self.model(x_noisy, t, **cond)
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
      return forward_call(*input, **kwargs)
    File "/path-to-auto1111-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1329, in forward
      out = self.diffusion_model(x, t, context=cc)
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
      return forward_call(*input, **kwargs)
    File "/path-to-auto1111-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 233, in forward2
      return forward(*args, **kwargs)
    File "/path-to-auto1111-webui/extensions/sd-webui-controlnet/scripts/hook.py", line 176, in forward
      control = param.control_model(x=x_in, hint=param.hint_cond, timesteps=timesteps, context=context)
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
      return forward_call(*input, **kwargs)
    File "/path-to-auto1111-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 115, in forward
      return self.control_model(*args, **kwargs)
    File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
      return forward_call(*input, **kwargs)
    File "/path-to-auto1111-webui/extensions/sd-webui-controlnet/scripts/cldm.py", line 380, in forward
      h += guided_hint
  RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0
  ```
</details>
Can be related to #11

**Comment by LightChaser666** [comment]
Please try the latest version, where I made a logically correction for all underlying code.

**Comment by binary-zero-one** [comment]
Commit 058013db80bdaafdcfa28b62c1f5e228831c2211
Now the picture doesn't look stretched out, but like a blurred transition from one shape to another with an offset
<details>
  <summary>UI Latest Commit</summary>
  
  ![ui_058013db](https://user-images.githubusercontent.com/75141398/227053296-871ce039-5759-4b15-bb8d-0eb834125fe3.png)
</details>

**Comment by pkuliyi2015** [comment]
I now know what happens. This is due to I didn't recover the modified ControlNet tensors when the batch ends. I will fix it very soon.

**Comment by pkuliyi2015** [comment]
Should be OK now. Please have a test.

**Comment by binary-zero-one** [comment]
@pkuliyi2015, please reopen, regression between 0ab4e2479e68a415d51c0b4fa331055b51e3d4a4..27a38c00675a6c1b376f3a04b97031a968fdaccc

**Comment by pkuliyi2015** [comment]
Hello, the problem is due to my friends’ refactoring. I will check this again.

**Comment by pkuliyi2015** [comment]
Hello, please have a try on the new version to see if it works normally.
