### ISSUE TITLE
RuntimeError of Region Prompt Control

### ISSUE THREAD

**Issue by bugtig6351** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#48]
使用Region Prompt Control的时候出现RuntimeError, 取消勾选Region Prompt Control时正常
插件版本已经更新至最新
![图片](https://user-images.githubusercontent.com/48248786/226533623-6d7a3d8f-7f9b-4d69-baa0-17dbfce0cf0d.png)

```
[Tiled Diffusion] upscaling image with Lanczos...
[Tiled Diffusion] ControlNet found, MultiDiffusion-ControlNet support is enabled.
MultiDiffusion hooked into Euler a sampler. Tile size: 96x96, Tile batches: 8, Batch size: 1
MultiDiffusion Sampling:   6%|████▊                                                                                 | 8/144 [01:20<22:51, 10.09s/it]
[Tiled VAE]: input_size: torch.Size([1, 3, 1728, 1152]), tile_size: 960, padding: 32
[Tiled VAE]: split to 2x2 = 4 tiles. Optimal tile size 544x832, original tile size 960x960
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 640 x 960 image
[Tiled VAE]: Executing Encoder Task Queue: 100%|█████████████████████████████████████████████████████████████████| 364/364 [00:01<00:00, 326.79it/s]
[Tiled VAE]: Done in 4.151s, max VRAM alloc 1123.737 MB
  0%|                                                                                                                         | 0/7 [00:03<?, ?it/s]
Error completing request  13%|███████████                                                                            | 8/63 [00:02<00:17,  3.11it/s] 
Arguments: ('task(wpz0s212znmet5m)', 0, 'best quality, extremely clear', '(worst quality, low quality:1.4), (blurry:1.3),(EasyNeagtive:1.1), watermark, bad_prompt_version2', [], <PIL.Image.Image image mode=RGBA size=768x1152 at 0x1863C75F4F0>, None, {'image': <PIL.Image.Image image mode=RGBA size=768x1152 at 0x1863C75D4B0>, 'mask': <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=768x1152 at 0x1863C75DD80>}, None, None, None, None, 20, 0, 4, 0, 0, False, False, 1, 1, 7, 1.5, 0.3, -1.0, -1.0, 0, 0, 0, False, 768, 512, 0, 0, 32, 0, '', '', '', '', 0, '<span>(No stats yet, run benchmark in VRAM Estimator tab)</span>', True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1, 'Lanczos', 1.5, False, True, 1, True, 1, 0.02, 0.19, 0.2, 0.2, 'holding a book', 'bad hands', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', True, True, True, True, 0, 960, 64, False, False, '#000000', False, None, None, <scripts.external_code.ControlNetUnit object at 0x00000186242DB4C0>, <scripts.external_code.ControlNetUnit object at 0x00000186242E8520>, None, '', 'Get Tags', False, 1, 0.15, False, 'OUT', ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, True, -1.0, '\n            <h3><strong>Combinations</strong></h3>\n            Choose a number of terms from a list, in this case we choose two artists\n            <code>{2$$artist1|artist2|artist3}</code>\n            If $$ is not provided, then 1$$ is assumed.\n            <br>\n            A range can be provided:\n            <code>{1-3$$artist1|artist2|artist3}</code>\n            In this case, a random number of artists between 1 and 3 is chosen.\n            <br/><br/>\n\n            <h3><strong>Wildcards</strong></h3>\n            <p>Available wildcards</p>\n            <ul>\n        <li>__artist__</li><li>__background__</li><li>__clothes__</li><li>__clotheslow__</li><li>__clothesup__</li><li>__color__</li><li>__expression__</li><li>__hair style__</li><li>__hairornament__</li><li>__hat__</li><li>__ornament__</li><li>__pose__</li><li>__shoes__</li><li>__sock__</li><li>__style__</li></ul>\n            <br/>\n            <code>WILDCARD_DIR: scripts/wildcards</code><br/>\n            <small>You can add more wildcards by creating a text file with one term per line and name is mywildcards.txt. Place it in scripts/wildcards. <code>__mywildcards__</code> will then become available.</small>\n        ', '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, 50, False, 4.0, '', 10.0, 'Linear', 3, False, 30.0, True, False, False, 0, 0.0, 'Lanczos', 1, True, 0, 0, 0.0001, 75, 0.0, False, 10.0, 30.0, True, 0.0, 'Lanczos', 1, 0, 0, 75, 0.0001, 0.0, False, False, False, 'Euler a', 0.95, 0.75, '0.75:0.95:5', '0.2:0.8:5', 'zero', 'pos', 'linear', 0.2, 0.0, 0.75, None, 'Lanczos', 1, 0, 0) {}
Traceback (most recent call last):
  File "D:\Downloads\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\Downloads\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\modules\img2img.py", line 171, in img2img
    processed = process_images(p)
  File "D:\Downloads\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "D:\Downloads\stable-diffusion-webui\modules\processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\Downloads\stable-diffusion-webui\modules\processing.py", line 1054, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "D:\Downloads\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 324, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Downloads\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "D:\Downloads\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 324, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 125, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": [cond_in[a:b]], "c_concat": [image_cond_in[a:b]]})
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\multidiffusion.py", line 71, in kdiff_repeat
    return self.compute_x_tile(x_in, repeat_func, custom_func)
  File "D:\Downloads\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\multidiffusion.py", line 153, in compute_x_tile
    x_tile_out = custom_func(x_tile, cond, uncond, index, bbox)
  File "D:\Downloads\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\multidiffusion.py", line 67, in custom_func 
    def custom_func(x, custom_cond, uncond, bbox_id, bbox): return self.kdiff_custom_forward(
  File "D:\Downloads\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\abstractdiffusion.py", line 219, in kdiff_custom_forward
    uncond_out = forward_func(x_tile[cond_size:cond_size+uncond_size], sigma_in[cond_size:cond_size+uncond_size], cond={"c_crossattn": [
  File "D:\Downloads\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 125, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\Downloads\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 151, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\Downloads\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model       
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1570, in _call_impl
    result = forward_call(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 776, in forward
    h = module(h, emb, context)
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 324, in forward
    x = block(x, context=context[i])
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 259, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "D:\Downloads\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\Downloads\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 129, in forward   
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "D:\Downloads\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 262, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1533, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Downloads\stable-diffusion-webui\modules\sd_hijack_optimizations.py", line 342, in xformers_attention_forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=get_xformers_flash_attention_op(q, k, v))
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 196, in memory_efficient_attention
    return _memory_efficient_attention(
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 292, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 312, in _memory_efficient_attention_forward  
    out, *_ = op.apply(inp, needs_gradient=False)
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\flash.py", line 235, in apply
    out, softmax_lse = cls.OPERATOR(
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\torch\_ops.py", line 504, in __call__
    return self._op(*args, **kwargs or {})
  File "D:\Downloads\stable-diffusion-webui\venv\lib\site-packages\xformers\ops\fmha\flash.py", line 59, in _flash_fwd
    lse = _C_flashattention.fwd(
RuntimeError: Expected batch_size > 0 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```

**Comment by pkuliyi2015** [comment]
应该已经修复
