### ISSUE TITLE
ImportError: cannot import name 'BlendMode' from 'methods'

### ISSUE THREAD

**Issue by szocpaul** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#57]
Hello!

I'm getting this error message. Can you please take a look into it?

```
Restarting UI...
Error loading script: tilediffusion.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 64, in <module>
    from methods import MultiDiffusion, MixtureOfDiffusers, splitable, BlendMode
ImportError: cannot import name 'BlendMode' from 'methods' (D:\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\__init__.py)

Loading Unprompted v7.9.1 by Therefore Games
(SETUP) Initializing Unprompted object...
(SETUP) Loading configuration files...
(SETUP) Debug mode is False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 9.0s (list extensions: 2.7s, load scripts: 1.0s, create ui: 4.9s, gradio launch: 0.2s).
```

**Comment by szocpaul** [comment]
After restart the A111 the issue is solved.
