### ISSUE TITLE
Error when HiRes.Fix is ​​enabled

### ISSUE THREAD

**Issue by SeBL4RD** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#63]
When I want to activate the HiRes.Fix, the generation crashes and I have this error message. It happened since one of the recent updates (yesterday or this morning).

```
Error completing request
Arguments: ('task(pnu2dtxsswv0011)', 'close-up to a nymph , <lora:LeahLora:1>, with curly golden hair , and leafy dress , she comb her hair , on a mossy log , near a crystal-clear lake , in a magical forest , with glowing mushrooms , and fairies, stockings, lace, nostalgia, sexy, a small pendant, majestic oil painting by Ed Blinkey, Atey Ghailan, Studio Ghibli, by Jeremy Mann, Greg Manchess, Antonio Moro, trending on ArtStation, trending on CGSociety, Intricate, High Detail, Sharp focus, dramatic, photorealistic painting art by midjourney and greg rutkowski\n', 'cartoon, 3d, ((disfigured)), ((bad art)), ((deformed)),((extra limbs)),((close up)),((b&w)), wierd colors, blurry, (((duplicate))), ((morbid)), ((mutilated)), out of frame, extra fingers, mutated hands, ((poorly drawn hands)), ((poorly drawn face)), (((mutation))), (((deformed))), ((ugly)), blurry, ((bad anatomy)), (((bad proportions))), ((extra limbs)), cloned face, (((disfigured))), out of frame, ugly, extra limbs, (bad anatomy), gross proportions, (malformed limbs), ((missing arms)), ((missing legs)), (((extra arms))), (((extra legs))), mutated hands, (fused fingers), (too many fingers), (((long neck))), Photoshop, video game, ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, mutation, mutated, extra limbs, extra legs, extra arms, disfigured, deformed, cross-eye, body out of frame, blur, bad art, bad anatomy, 3d render, freckles, watermark, hat', [], 50, 0, False, False, 1, 1, 13, -1.0, -1.0, 0, 0, 0, False, 512, 512, True, 0.2, 2.95, '4x-UltraSharp', 50, 0, 0, ['Model hash: c35782bad8'], 0, True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, True, True, True, True, 0, 1600, 192, False, '', 0, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, None, 'Refresh models', <scripts.external_code.ControlNetUnit object at 0x0000014993843430>, <scripts.external_code.ControlNetUnit object at 0x0000014993842290>, <scripts.external_code.ControlNetUnit object at 0x0000014993841930>, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 924, in sample
    samples = self.sampler.sample_img2img(self, samples, noise, conditioning, unconditional_conditioning, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 324, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 324, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 138, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": c_crossattn, "c_concat": [image_cond_in[a:b]]})
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\multidiffusion.py", line 79, in kdiff_repeat
    return self.compute_x_tile(x_in, repeat_func, custom_func)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\multidiffusion.py", line 118, in compute_x_tile
    assert H == self.h and W == self.w
AssertionError
```

**Comment by pkuliyi2015** [comment]
Currently we do not support the high res option. That is a second i2i. We are considering injecting a new algorithm to do so.

**Comment by SeBL4RD** [comment]
> Currently we do not support the high res option. That is a second i2i. We are considering injecting a new algorithm to do so.

?? But it was working 2 days ago, 
why doesn't it work anymore? HiRes Fix is ​​very useful...

**Comment by pkuliyi2015** [comment]
At that time multi diff i2i is broken

**Comment by pkuliyi2015** [comment]
Please update and check again. I now silently disable multidiff at highres stage so it should work smoothly as two days ago.

**Comment by SeBL4RD** [comment]
> > > Currently we do not support the high res option. That is a second i2i. We are considering injecting a new algorithm to do so.
> > 
> > 
> > ?? But it was working 2 days ago, why doesn't it work anymore? HiRes Fix is ​​very useful...
> 
> Please update and check again. I now silently disable multidiff at highres stage so it should work smoothly as two days ago.

Still the same error

**Comment by pkuliyi2015** [comment]
You may not update correctly because I have removed the line in my code. There is no "assert" anymore. Please try to delete the extension and download again.

**Comment by SeBL4RD** [comment]
> 

![Screenshot_107](https://user-images.githubusercontent.com/45276149/227736772-aee93104-84ad-44c8-9cd5-efc5f1903094.png)
![Screenshot_106](https://user-images.githubusercontent.com/45276149/227736773-69d30952-f784-4c6f-b8a8-15d4be65348e.png)


> You may not update correctly because I have removed the line in my code. There is no "assert" anymore.
> 
> I mean, this line "assert H == self.h and W == self.w" has been removed.
> 
> Please try to delete the extension and download again.

**Comment by pkuliyi2015** [comment]
Then what's your error? Shouldn't be the same.

**Comment by SeBL4RD** [comment]
> Then what's your error? Shouldn't be the same. Would you mind give the error?

Sorry, my screenshots are from before I saw you telling me to remove the extension.
It seems to work, SD does not crash when doing the HiResFix, but I have a CUDA crash, while I only ask for a HiresFix at 1500x1500 pixels, whereas before I could go up to more than 2200x1200 without problems. I use the same settings as before

**Comment by pkuliyi2015** [comment]
If it is CUDA error please gives the screenshots too. I suspect it's from VAE.

**Comment by SeBL4RD** [comment]
Wait, 2138x1203 not crash, when 1500x1500 CUDA crash... I don't understand anything

**Comment by pkuliyi2015** [comment]
You mean current version? or comparing with previous version?
We have done a CUDA VRAM test that we don't make any leakage in the process.

**Comment by SeBL4RD** [comment]
forget it, I think I must have consumed slightly too much Vram, my CUDA crashes must have been related to that.
In any case, a huge thank you for your fabulous work.
Serious to your extension, I can finally make great images in 16/9 with a decent resolution. It's just amazing to be able to do this with my poor 2070 Super.

**Comment by SeBL4RD** [comment]
And of course, thank you very much for your speed of intervention, you solved the problem very quickly, thank you!

**Comment by SeBL4RD** [comment]
Ah, finally maybe not : 
1500x1500 hires do a CUDA crash at end : 

```
Error completing request
Arguments: ('task(o78ntjwr2ui85un)', 'close-up to a nymph , <lora:LeahLora:1>, with curly golden hair , and leafy dress , she comb her hair , on a mossy log , near a crystal-clear lake , in a magical forest , with glowing mushrooms , and fairies, stockings, lace, nostalgia, sexy, a small pendant, majestic oil painting by Ed Blinkey, Atey Ghailan, Studio Ghibli, by Jeremy Mann, Greg Manchess, Antonio Moro, trending on ArtStation, trending on CGSociety, Intricate, High Detail, Sharp focus, dramatic, photorealistic painting art by midjourney and greg rutkowski\n', 'cartoon, 3d, ((disfigured)), ((bad art)), ((deformed)),((extra limbs)),((close up)),((b&w)), wierd colors, blurry, (((duplicate))), ((morbid)), ((mutilated)), out of frame, extra fingers, mutated hands, ((poorly drawn hands)), ((poorly drawn face)), (((mutation))), (((deformed))), ((ugly)), blurry, ((bad anatomy)), (((bad proportions))), ((extra limbs)), cloned face, (((disfigured))), out of frame, ugly, extra limbs, (bad anatomy), gross proportions, (malformed limbs), ((missing arms)), ((missing legs)), (((extra arms))), (((extra legs))), mutated hands, (fused fingers), (too many fingers), (((long neck))), Photoshop, video game, ugly, tiling, poorly drawn hands, poorly drawn feet, poorly drawn face, out of frame, mutation, mutated, extra limbs, extra legs, extra arms, disfigured, deformed, cross-eye, body out of frame, blur, bad art, bad anatomy, 3d render, freckles, watermark, hat', [], 50, 0, False, False, 1, 1, 13, 4066508902.0, -1.0, 0, 0, 0, False, 512, 512, True, 0.15, 2.95, 'ESRGAN 4x', 50, 0, 0, ['Model hash: c35782bad8'], 0, True, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, True, True, True, True, 0, 1600, 176, False, '', 0, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, None, 'Refresh models', <scripts.external_code.ControlNetUnit object at 0x0000018676ED1600>, <scripts.external_code.ControlNetUnit object at 0x0000018676ED1EA0>, <scripts.external_code.ControlNetUnit object at 0x0000018676ED1DB0>, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 924, in sample
    samples = self.sampler.sample_img2img(self, samples, noise, conditioning, unconditional_conditioning, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 324, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 324, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 148, in forward
    sd_samplers_common.store_latent(x_out[0:uncond.shape[0]])
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_common.py", line 58, in store_latent
    shared.state.assign_current_image(sample_to_image(decoded))
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_common.py", line 46, in sample_to_image
    return single_sample_to_image(samples[index], approximation)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_samplers_common.py", line 37, in single_sample_to_image
    x_sample = processing.decode_first_stage(shared.sd_model, sample.unsqueeze(0))[0]
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\processing.py", line 423, in decode_first_stage
    x = model.decode_first_stage(x)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py", line 486, in __call__
    return self.net.original_forward(x)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 637, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 131, in forward
    h = self.norm1(h)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\normalization.py", line 273, in forward
    return F.group_norm(
  File "C:\Users\Seb\Desktop\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\functional.py", line 2528, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.16 GiB (GPU 0; 8.00 GiB total capacity; 3.47 GiB already allocated; 0 bytes free; 7.04 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF


```

**Comment by pkuliyi2015** [comment]
Oh this can be very easily fixed. You just lower down your tiled VAE decoder tile size.

**Comment by SeBL4RD** [comment]
> 

1500x1500 Hires and 2100x1200 are not supposed to have the same amount of pixels? 
I will try it right now

**Comment by SeBL4RD** [comment]
Bro, you fixed ControlNet support, OpenPose works back, i love you man.

**Comment by pkuliyi2015** [comment]
It is only because the peak of VRAM goes slightly bigger, when your height & width is not very dividable by the tile size. 
By the way the recommended VAE tile size only work when you don't use ControlNet or HyperNet or other things that take your VRAM away. So if you use many types of these things it may not proper anymore, you need adjust them smaller.

**Comment by SeBL4RD** [comment]
> 

yeah, obviously, i tried without ControlNet, i know models from are greedy with Vram

**Comment by SeBL4RD** [comment]
You were right, reduced Decoder Tile Size from 176 to 128, no crash CUDA in 1500x1500.
Again, ty so much

**Comment by pkuliyi2015** [comment]
You are welcome. Thanks for your feedback too.
