### ISSUE TITLE
更新最新gradio 3.23.0后，tiled diffusion功能界面消失

### ISSUE THREAD

**Issue by LieDeath** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#68]
![image](https://user-images.githubusercontent.com/115352572/227766310-aef8c5cd-8993-4cab-81a5-8bab1309b4c9.png)
真奇怪，只剩tiled vae一个功能了。
```
Error loading script: tilediffusion.py
Traceback (most recent call last):
  File "D:\AI6\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\AI6\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI6\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 65, in <module>
    from methods import abstractdiffusion, multidiffusion, mixtureofdiffusers
  File "D:\AI6\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\__init__.py", line 1, in <module>
    from .multidiffusion import MultiDiffusion
  File "D:\AI6\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\multidiffusion.py", line 7, in <module>
    from .abstractdiffusion import TiledDiffusion
  File "D:\AI6\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\abstractdiffusion.py", line 13, in <module>
    class TiledDiffusion:
  File "D:\AI6\stable-diffusion-webui\extensions\multidiffusion-upscaler-for-automatic1111\methods\abstractdiffusion.py", line 15, in TiledDiffusion
    def __init__(self, p:StableDiffusionProcessing, sampler:Sampler):
NameError: name 'Sampler' is not defined
```

已确认故障commit是 d66337c

**Comment by pkuliyi2015** [comment]
卧槽有这档子事么我试试

**Comment by pkuliyi2015** [comment]
啊这没有啊，我这里全更新了也能正常用。你不妨试试删了插件重新安装，这种东西一般是莫名其妙的缓存错误

**Comment by sky202203** [comment]
![2023-03-26 18 36 45](https://user-images.githubusercontent.com/122595656/227770175-0fb3d95c-3669-48ee-b45a-745ad831fc21.png)

不見了

**Comment by LieDeath** [comment]
> 啊这没有啊，我这里全更新了也能正常用。你不妨试试删了插件重新安装，这种东西一般是莫名其妙的缓存错误

在新实例上完整安装了这个插件就正常了，可能确实是缓存错误。但是git pull上来的就会这样子。

**Comment by LieDeath** [comment]
> ![2023-03-26 18 36 45](https://user-images.githubusercontent.com/122595656/227770175-0fb3d95c-3669-48ee-b45a-745ad831fc21.png)
> 
> 不見了

你重新安裝插件就行了，確實是緩存錯誤。

**Comment by LieDeath** [comment]
> 啊这没有啊，我这里全更新了也能正常用。你不妨试试删了插件重新安装，这种东西一般是莫名其妙的缓存错误

？又测试了一遍，我两个实例，一个可以一个不行，可以用的是之前没装插件的，不能用的是之前装了插件的，咄咄怪事。

**Comment by pkuliyi2015** [comment]
我稍微更新了一下去掉了调试部分，现在应该 可以了吧？

**Comment by LieDeath** [comment]
> 我稍微更新了一下去掉了调试部分，现在应该 可以了吧？

不行，太奇怪了。

**Comment by LieDeath** [comment]
> 我稍微更新了一下去掉了调试部分，现在应该 可以了吧？

目前曾经安装过multidiffusion的实例只能使用 86db257 及以前的版本，但是全新安装的示例可以使用 d66337c 及以后的版本，烦请查找一下 d66337c 到底更新了什么而导致旧实例无法工作。

**Comment by pkuliyi2015** [comment]
实际上是把utils包拆出来了。我看看是不是有包名冲突。

**Comment by LieDeath** [comment]
> 实际上是把utils包拆出来了。我看看是不是有包名冲突。

抓到冲突了，是deforum这个插件https://github.com/deforum-art/deforum-for-automatic1111-webui

**Comment by pkuliyi2015** [comment]
你再试试看 我现在移除了所有的包 并且重命名了路径

**Comment by LieDeath** [comment]
> 你再试试看 我现在移除了所有的包 并且重命名了路径

感谢，彻底解决了，占用了你那么多宝贵的时间。

**Comment by sky202203** [comment]
可以了, 十分感謝你!!!

> 你再试试看 我现在移除了所有的包 并且重命名了路径

可以了, 十分感謝你!!!
