### ISSUE TITLE
get this error that makes me restart the program

### ISSUE THREAD

**Issue by gsgoldma** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#8]
happens when it finished an image right after 100% or if I interrupt it before it's done.

Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui\modules\call_queue.py", line 33, in f
    shared.state.begin()
  File "D:\stable-diffusion-webui\modules\shared.py", line 231, in begin
    devices.torch_gc()
  File "D:\stable-diffusion-webui\modules\devices.py", line 59, in torch_gc
    torch.cuda.empty_cache()
  File "D:\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\memory.py", line 125, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by pkuliyi2015** [comment]
Hello, it is likely to be an environment or device errors. I don't know how to fix such problems too but normally when you switch to another device or colab it works smoothly. The root cause is the @perfcount decorator, you can try to remove that in your script，and have a test. The disable live preview will also help.
