### ISSUE TITLE
'BBoxSettings' is not defined

### ISSUE THREAD

**Issue by Nirvaxstiel** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#98]
Installed extension and wasn't able to load. Stack trace from CLI:

```Error loading script: tilediffusion.py
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-automatic1111\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\stable-diffusion-webui-automatic1111\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\stable-diffusion-webui-automatic1111\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 78, in <module>
    class Script(scripts.Script):
  File "E:\stable-diffusion-webui-automatic1111\extensions\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py", line 459, in Script
    bbox_settings: Dict[int, BBoxSettings]
NameError: name 'BBoxSettings' is not defined```

**Comment by pkuliyi2015** [comment]
This is a cache error. Just delete the extension in the "extensions" folder, reinstall the extension, and restart the ui then everything should be fine.

**Comment by Nirvaxstiel** [comment]
Nice to know it was just cached badly. Thanks!
